### ISSUE TITLE
NullPointerException in JStringArray to String code

### ISSUE THREAD

**Issue by psibi** [typelead/eta#135]
This is the code which we were discussing in gitter a few days ago.

```
foreign import java unsafe "@static eta.examples.Utils.getNames" getNames :: JStringArray

-- https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Array.html#getLength(java.lang.Object)
foreign import java unsafe "@static java.lang.reflect.Array.getLength" getLength :: (Extends a Object) => a -> Int

-- https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Array.html#newInstance(java.lang.Class,%20int)
foreign import java unsafe "@static java.lang.reflect.Array.newInstance" newArray :: JClass -> Int -> Object

-- https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Array.html#get(java.lang.Object,%20int)
foreign import java unsafe "@static java.lang.reflect.Array.get" arrayGet :: (Extends a Object) => a -> Int -> Object 

conv :: JStringArray -> [JString] 
conv arr = map (unsafeCast . arrayGet arr') [0..len - 1] 
    where len = getLength arr
          arr' = newArray (getClass "java.lang.String") len
```

It throws the following error:

```
Preprocessing executable 'eta-ffi' for eta-ffi-0.1.0.0...
[1 of 2] Compiling FFI              ( src/FFI.hs, dist/build/eta-ffi/eta-ffi-tmp/FFI.jar )
[2 of 2] Compiling Main             ( src/Main.hs, dist/build/eta-ffi/eta-ffi-tmp/Main.jar ) [FFI changed]
Linking dist/build/eta-ffi/eta-ffi.jar ...
Running eta-ffi...
Exception in thread "main" java.lang.NullPointerException
        at ghczmprim.ghc.CString$unpackCStringzh.enter(Unknown Source)
        at base.ghc.Pack$unpackCString.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:116)
        at eta.runtime.apply.Apply$8.enter(Apply.java:75)
        at eta.runtime.thunk.Ap2Upd.thunkEnter(Ap2Upd.java:21)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:19)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
        at base.ghc.Show$showLitString.enter(Unknown Source)
        at main.Main$satzus6MR.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:19)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
        at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.Apply$2.enter(Apply.java:21)
        at eta.runtime.exception.StgException$7.enter(StgException.java:183)
        at main.Main$main3.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
        at eta.runtime.stg.Capability.schedule(Capability.java:246)
        at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
        at eta.runtime.Rts.evalLazyIO(Rts.java:92)
        at eta.runtime.Rts.hsMain(Rts.java:37)
        at eta.main.main(Unknown Source)
```

I have the entire code here which reproduces this error: https://github.com/psibi/eta-ffi/tree/null-pointer-exception 

Note that the branch name is `null-pointer-exception` and not `master`.

**Comment by rahulmutt** [comment]
If you switch `unsafeCast . arrayGet arr'` to `unsafeCast . arrayGet arr` it fixes the problem.

**Comment by psibi** [comment]
Ah, silly me.
