### ISSUE TITLE
Bug with Unicode strings: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by flyfish30** [typelead/eta#180]
Source Code:
```haskell
main :: IO ()
main = mapM_ putStrLn $ sierpinskiS 2

infixl 5 ===
(===) = (  )

infixl 5 |||
(|||) = zipWith (  )

center n = map ((spaces   ) . (   spaces))
    where spaces = replicate (2 ^ (n - 1)) ' '

sierpinskiS :: Int -> [[Char]]
sierpinskiS 0 = ["△ "]
sierpinskiS n = center n s
                ===
                (s ||| s)
    where s = sierpinskiS (n - 1)
```

Output:
```shell
Compiling

**Comment by rahulmutt** [comment]
Can you describe the exact behaviour a bit more precisely? Did it hang without returning a result?

**Comment by flyfish30** [comment]
This program has been successful compiled by ghc 8.0.1 and output is show in bellow.
   △    
  △ △   
 △   △  
△ △ △ △ 

In this playground, the file can not compiled.

**Comment by rahulmutt** [comment]
I mean why wasn't it compiled? Did it show an error message from Eta or a Java runtime exception or did it just hang on compilation?

**Comment by flyfish30** [comment]
The compile time is too long, the error message is show in bellow:
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 4
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:206)
at Sandbox.main(Sandbox.java:22)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
at ghczmprim.ghc.CString$unpackzus18DO.enter(Unknown Source)
at ghczmprim.ghc.CString$satzus18FQ.thunkEnter(Unknown Source)
at eta.runtime.thunk.StgInd.enter(StgInd.java:19)
at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
at base.ghc.Base$zpzp.enter(Unknown Source)
at base.ghc.Base$satzusAD0.thunkEnter(Unknown Source)
at eta.runtime.thunk.StgInd.enter(StgInd.java:19)
at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
at base.ghc.io.handle.Text$zdwa8.enter(Unknown Source)
at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
at main.Main$main3.enter(Unknown Source)
at main.Main$main1.enter(Unknown Source)
at eta.runtime.apply.StgFun.apply(StgFun.java:19)
at eta.runtime.apply.Apply$2.enter(Apply.java:21)
at eta.runtime.exception.StgException$7.enter(StgException.java:183)
at main.Main$main4.enter(Unknown Source)
at main.Main$DZCmain.enter(Unknown Source)
at eta.runtime.apply.StgFun.apply(StgFun.java:19)
at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
at eta.runtime.stg.Capability.schedule(Capability.java:246)
at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
at eta.runtime.Rts.evalLazyIO(Rts.java:92)
at eta.runtime.Rts.hsMain(Rts.java:37)
at eta.main.main(Unknown Source)
at Sandbox$1.call(Sandbox.java:19)
at Sandbox$1.call(Sandbox.java:17)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by rahulmutt** [comment]
Thanks! That's helpful. My gut tells me it's a problem with the Unicode triangle. Can you try replacing that with a normal ASCII character and let me know what happens?

**Comment by flyfish30** [comment]
It is success when I replace the unicode triangle '△' with normal ASCII '*'.

**Comment by jneira** [comment]
Some tests in case the can help:
* `print $ BSUTF8.fromString "ñ"`:
  * it should print "\195\177" but it throws the `ArrayIndexOutOfBoundException` exception
  * [trace.txt](https://github.com/typelead/eta/files/980945/trace.txt)
* `print $ BSUTF8.fromString "ño"`
  * prints "\195\177" but it should be "\195\177o"
  * [trace2.txt](https://github.com/typelead/eta/files/980951/trace2.txt)

**Comment by jneira** [comment]
comment updated!

**Comment by jneira** [comment]
In fact you get the same behaviour without `Data.ByteString.UTF8.fromString`, simply with `print "ñ"`  and `print "ño"`

**Comment by jneira** [comment]
i test both cases with the changes in #350 and they works ok!
