### ISSUE TITLE
conduit / resourcet runtime cast exception

### ISSUE THREAD

**Issue by AlexeyRaga** [typelead/eta#204]
I have this code:

```
{-# LANGUAGE MagicHash, OverloadedStrings #-}
module Main
where

import Java
import Java.Array
import Data.Conduit
import Data.Conduit.List as L
import Control.Monad.IO.Class
import Control.Monad (void)
import Control.Monad.Trans.Resource

src :: MonadResource m => Int -> Source m ()
src n = 
  bracketP newRes closeRes yieldRes
  where
    newRes = 
      print "allocating nothing"

    closeRes res =
      print "nothing to close"

    yieldRes res = yield res


main :: IO ()
main = do
  res <- runConduitRes $ src 10 .| L.take 1
  print res

```

It compiles fine, but at runtime I get:

```
Exception in thread "main" java.lang.ClassCastException: resourcetzm1zi1zi9.control.monad.trans.resource.Internal$ReleaseMapD cannot be cast to resourcetzm1zi1zi9.control.monad.trans.resource.Internal$ReleaseKeyD
	at conduitzm1zi2zi8.data.conduit.internal.Conduit$xzus1E8Q.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:22)
	at eta.runtime.apply.Apply$Ap0Fast.enter(Apply.java:34)
	at conduitzm1zi2zi8.data.conduit.internal.Conduit$satzus1E8Y.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:116)
	at eta.runtime.apply.Apply$ApPFast.enter(Apply.java:96)
	at conduitzm1zi2zi8.data.conduit.internal.Conduit$lvl11zus1DHY.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.thunk.StgThunk.apply(StgThunk.java:131)
	at eta.runtime.apply.Apply$ApPFast.enter(Apply.java:96)
	at eta.runtime.thunk.Ap2Upd.thunkEnter(Ap2Upd.java:21)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.thunk.StgThunk.apply(StgThunk.java:71)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at main.Main$satzusN78.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at main.Main$zdLrN0Da2.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:172)
	at eta.runtime.apply.ApPV.stackEnter(ApPV.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at main.Main$zdLrN0Da2.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:172)
	at eta.runtime.apply.ApPV.stackEnter(ApPV.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main16.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Can you make an example that I can compile & run (maybe upload on your Kafka client)? I can't do a proper trace with just the information you have given me.

**Comment by AlexeyRaga** [comment]
Updated an issue with a reproducible minimalistic example
