### ISSUE TITLE
Builder (ByteString/Binary etc) return Prelude.undefined

### ISSUE THREAD

**Issue by aktowns** [typelead/eta#221]
Not sure if this is related to lack of C FFI? Playing around it appears

```haskell
-- Data-ByteString-Internal
mallocByteString :: Int -> IO (ForeignPtr a)
````
Always returns a null pointer, they also 'show' as abnormally large
`0x0000000000000000000000000000000000000000000000000000000000000000`.  digging through the source for `Data,ByteString.Builder` it looks like
new buffers are created this way, somehow eventually they end up as `undefined`. A small example
that replicates it is:

```haskell
import qualified Data.ByteString.Builder as B
main = print $ B.toLazyByteString $ B.byteString "a"
```
which throws
```
Prelude.undefined
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1333)
	at eta.runtime.RtsMessages.errorBelch(RtsMessages.java:32)
	at eta.base.Utils.errorBelch(Utils.java:154)
	at base.ghc.conc.Sync$satzusEKLU.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD25E.enter(Unknown Source)
	at base.ghc.Foreign$satzusD265.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$satzusEKLV.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD25E.enter(Unknown Source)
	at base.ghc.Foreign$satzusD265.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$zdLrEKHClvl6.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at base.ghc.TopHandler$satzusI5CQ.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```
(Similar outcome for `Binary.Builder`, `Blaze.Builder` etc)

Also came across an odd one when trying to print a nullPtr

```haskell
import Foreign.ForeignPtr
main = print nullPtr
```
```
Exception in thread "main" java.lang.NoSuchMethodError: eta.integer.Utils.toUnsignedBigInteger(I)Ljava/math/BigInteger;
	at integer.ghc.integer.Type$wordToInteger.enter(Unknown Source)
	at base.ghc.Ptr$satzus5YFJ.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at integer.ghc.integer.Type$ltIntegerzh.enter(Unknown Source)
	at integer.ghc.integer.Type$ltInteger.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.ApPP.stackEnter(ApPP.java:19)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.Numeric$showIntAtBase.enter(Unknown Source)
	at base.ghc.Ptr$satzus5YFV.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main3.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
You can check out the `bytestring` patch here, the C FFI calls are replaced with Java FFI calls:

https://github.com/typelead/eta-hackage/blob/master/patches/bytestring-0.10.8.1.patch

It may be possible that there have might have been errors in functions that haven't been used by anyone yet. Until we get `test-framework-*` libraries ported, we can't run the existing tests to find all the bugs at once. We're pretty close to that - just need to port `regex-posix-base`.

There are some unimplemented I/O functions in `base` which are stubbed with `undefined` (my current work is getting those implemented). It maybe be one of those that are causing the error above. If so, I'll get them implemented now.

As for the second error, it seems to rather trivial mistake. That particular function was declared a `private` for some reason.

**Comment by rahulmutt** [comment]
Tracked down the `undefined`. `memcpy`, `memmove`, and `memset` in `Foreign.Marshal.Utils` haven't been implemented yet, although I've had to make separate implementations in the `array` and `bytestring` patches. You're welcome to take a stab at them, otherwise I'll push a fix by tomorrow.

**Comment by aktowns** [comment]
I'll take a stab at them today, thanks for looking into it. for the second one I was staring right at the function and completely missed it ha

**Comment by aktowns** [comment]
Had a go at the issues above, and came across something else a little odd

```haskell
{-# LANGUAGE OverloadedStrings, GHCForeignImportPrim, MagicHash, BangPatterns, ScopedTypeVariables #-}
module Main where

import Foreign.Ptr
import GHC.Word
import GHC.Prim
import GHC.Integer
import GHC.Exts

main :: IO ()
main = do
  print $ I# (addr2Int# nullAddr#)
  print nullPtr
```
which in eta returns
```
-1
0xffffffffffffffff
```
and on haskell returns 
```
0
0x0000000000000000
```

appears that `nullAddr#` on eta is returning -1 i traced it to  `nullAddrLit` then eventually `MachNullAddr` to eventually 

```
compiler/ETA/CodeGen/Utils.hs
27:cgLit MachNullAddr          = (jobject, aconst_null jobject)
```

Though I don't know enough about java internals to now if NULL is represented as -1 (i see a few JNI references where null objects are referred to as (jobject)0xFFFFFFFF)

**Comment by rahulmutt** [comment]
You can check out `eta.runtime.io.MemoryManager` that has the very basic implementation of off-heap memory and addressing via DirectByteBuffers. Basically, addressing starts from `0` so I had to use `-1` to distinguish the null address. We could just as well shift the first address to start at `1` or something and make null `0`.

**Comment by rahulmutt** [comment]
@aktowns Close if this fixed?
