### ISSUE TITLE
NPE for wai-servlet sample application

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#268]
Here's the stack trace I get:
```
java.lang.NullPointerException
	bytestring.data.bytestring.Internal$zdwunpackAppendCharsLazzy.enter(Unknown Source)
	wai.network.wai.Internal$satzusCZZL.thunkEnter(Unknown Source)
	eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	base.ghc.Base$zpzp.enter(Unknown Source)
	base.ghc.Base$satzusAQ8.thunkEnter(Unknown Source)
	eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	base.ghc.Base$zpzp.enter(Unknown Source)
	base.ghc.Base$satzusAQ8.thunkEnter(Unknown Source)
	eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	main.Main$zdfstableZZC0ZZCmainZZCMainZZCservShowReq2.enter(Unknown Source)
	main.Main$satzusPL3.enter(Unknown Source)
	eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	eta.runtime.apply.StgPAP.apply(StgPAP.java:172)
	eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	blaze_builder.blaze.bytestring.Builder$zdwa2zus1EEU.enter(Unknown Source)
	blaze_builder.blaze.bytestring.Builder$satzus1EJ0.enter(Unknown Source)
	eta.runtime.apply.StgFun.apply(StgFun.java:19)
	eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	blaze_builder.blaze.bytestring.Builder$zdwtoLazzyByteStringWith.enter(Unknown Source)
	main.Main$zdwa.enter(Unknown Source)
	main.Main$zdfstableZZC0ZZCmainZZCMainZZCservShowReq1.enter(Unknown Source)
	main.Main$zdfstableZZC0ZZCmainZZCMainZZCservShowReq.enter(Unknown Source)
	eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	eta.runtime.apply.StgPAP.apply(StgPAP.java:131)
	eta.runtime.apply.ApO.stackEnter(ApO.java:17)
	eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	base.java.TopHandler$satzusI9QQ.enter(Unknown Source)
	eta.runtime.apply.StgFun.apply(StgFun.java:19)
	eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	base.java.TopHandler$runJava1.enter(Unknown Source)
	base.java.TopHandler$runJava.enter(Unknown Source)
	eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	eta.runtime.apply.StgPAP.apply(StgPAP.java:131)
	eta.runtime.apply.ApO.stackEnter(ApO.java:17)
	eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	eta.runtime.stg.Capability.schedule(Capability.java:260)
	eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	eta.runtime.Rts.evalJava(Rts.java:107)
	network.wai.servlet.DefaultWaiServlet.service(Unknown Source)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```
@jneira, please share yours as well for running the default application. Also, you mentioned some of the applications work - can you share them so I can test them out as well?

**Comment by jneira** [comment]
Hi, compiling my tests:
* Showing a subset of request fields:
```haskell
appShowReq :: Application
appShowReq req respond = respond $ responseBuilder
  status200 [("Content-Type", "text/plain")] $
  (fromShow $ requestMethod req) <> (fromShow $ httpVersion req) <>
  (fromByteString $ rawPathInfo req) <> (fromByteString $ rawQueryString req)
```
  * The exception if you call without a query string is:
```
java.lang.NullPointerException
    at main.Main$zdwa5zusS37.enter(Unknown Source)
    at main.Main$a11zusS2F.enter(Unknown Source)
    at eta.runtime.apply.StgFun.apply(StgFun.java:138)
    at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
    at main.Main$zdLrRRHzdwa3.enter(Unknown Source)
    at main.Main$satzusS4W.enter(Unknown Source)
    at eta.runtime.apply.StgFun.apply(StgFun.java:138)
    at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
    at main.Main$zdLrRRIzdwa4.enter(Unknown Source)
    at main.Main$a10zusS28.enter(Unknown Source)
    at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
    at eta.runtime.apply.StgPAP.apply(StgPAP.java:172)
    at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
    at blazzezmbuilderzm0zi4zi0zi2.blaze.bytestring.Builder$zdwa2zus1EE5.enter(Unknown Source)
    at blazzezmbuilderzm0zi4zi0zi2.blaze.bytestring.Builder$satzus1EIB.enter(Unknown Source)
    at eta.runtime.apply.StgFun.apply(StgFun.java:19)
    at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
    at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
    at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
    at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
    at blazzezmbuilderzm0zi4zi0zi2.blaze.bytestring.Builder$zdwtoLazzyByteStringWith.enter(Unknown Source)
    at main.Main$satzusS5G.enter(Unknown Source)
    at eta.runtime.apply.StgFun.apply(StgFun.java:99)
    at eta.runtime.apply.ApO.stackEnter(ApO.java:17)
    at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
    at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
    at base.java.TopHandler$satzusI9KU.enter(Unknown Source)
    at eta.runtime.apply.StgFun.apply(StgFun.java:19)
    at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
    at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
    at base.java.TopHandler$runJava1.enter(Unknown Source)
    at base.java.TopHandler$runJava.enter(Unknown Source)
    at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
    at eta.runtime.apply.StgPAP.apply(StgPAP.java:131)
    at eta.runtime.apply.ApO.stackEnter(ApO.java:17)
    at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
    at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
    at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
    at eta.runtime.stg.Capability.schedule(Capability.java:260)
    at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
    at eta.runtime.Rts.evalJava(Rts.java:107)
    at network.wai.servlet.DefaultWaiServlet.service(Unknown Source)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```
* With this version if you call with whatever query string there is no error
----------------------------
* Showing the complete wai request (actual version in github):
```haskell
appShowReq :: Application
appShowReq req respond = respond $ responseBuilder
  status200 [("Content-Type", "text/plain")] $  fromShow req
```` 
* The exception is same as yours
----------------------------
Simple wai apps works too:
* With string literal (it's a bytestring cause OverloadedStrings)
```haskell
appSimple :: Application
appSimple _ respond = respond $
   responseLBS status200 [("Content-Type", "text/plain")] "Hello World"
```
* Using fromByteString and fromShow
```
appState :: MVar Integer -> Application
appState countRef _ respond = do
    modifyMVar countRef $ \count -> do
        let count' = count + 1
            msg = fromByteString "You are visitor number: " <>
                  fromShow count'
        responseReceived <- respond $ responseBuilder
            status200
            [("Content-Type", "text/plain")]
            msg
        return (count', responseReceived)
```

**Comment by jneira** [comment]
Hi, i've reproduced the error in a main app:
https://github.com/jneira/eta-test/blob/master/app/Main.hs
and generate the trace file:
[eta-test.trace.txt](https://github.com/typelead/eta/files/920966/eta-test.trace.txt)

**Comment by jneira** [comment]
At the end, it boils down to
```haskell
main = print $ show ByteString.empty
```
```
Exception in thread "main" java.lang.NullPointerException
        at bytestring.data.bytestring.Internal$zdwunpackAppendCharsLazzy.enter(Unknown Source)
        at main.Main$main7.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.Show$showLitString.enter(Unknown Source)
        at main.Main$main6.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.Show$showLitString.enter(Unknown Source)
        at base.ghc.Show$satzusW8C.enter(Unknown Source)
        at base.ghc.Base$zpzp.enter(Unknown Source)
        at base.ghc.Base$satzusAQ8.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
        at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
        at main.Main$main8.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
        at eta.runtime.stg.Capability.schedule(Capability.java:260)
        at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
        at eta.runtime.Rts.evalLazyIO(Rts.java:95)
        at eta.runtime.Rts.hsMain(Rts.java:38)
        at eta.main.main(Unknown Source)
```

**Comment by jneira** [comment]
Well, after some investigation:
* ByteString.empty:
```haskell
empty :: ByteString
empty = PS nullForeignPtr 0 0


nullForeignPtr :: ForeignPtr Word8
nullForeignPtr = ForeignPtr nullAddr# (error "nullForeignPtr")
```
* it seems `nullAddr#` is directly java `null`
* Code of ByteString.Internal:
```haskell
unpackAppendBytesLazy :: ByteString -> [Word8] -> [Word8]
unpackAppendBytesLazy (PS fp off len) xs
  | len <= 100 = unpackAppendBytesStrict (PS fp off len) xs
  | otherwise  = unpackAppendBytesStrict (PS fp off 100) remainder
  where
    remainder  = unpackAppendBytesLazy (PS fp (off+100) (len-100)) xs
```
  * so `fp` is java `null`
* Code decompiled of `Internal$zdwunpackAppendCharsLazzy.enter`:
```java
public void enter(StgContext paramStgContext)
  {
    ByteBuffer localByteBuffer1 = (ByteBuffer)paramStgContext.O(1);
    StgClosure localStgClosure1 = paramStgContext.R(2);
    int i = paramStgContext.I(1);
    int j = paramStgContext.I(2);
    StgClosure localStgClosure2 = paramStgContext.R(3);
    int k = j > 100 ? 0 : 1;
    int n;
    Object localObject;
    if (((StgConstr)ghc_prim.ghc.Types.Bool_table[k]).getTag() != 1)
    {
      int m = i - 1;
      n = m + j;
      ByteBuffer localByteBuffer2 = (ByteBuffer)localByteBuffer1.duplicate().position(localByteBuffer1.position() + n);
      int i2 = i - 1;
      ByteBuffer localByteBuffer4 = (ByteBuffer)localByteBuffer1.duplicate().position(localByteBuffer1.position() + i2);
      paramStgContext.O(1, localByteBuffer4);
      paramStgContext.O(2, localByteBuffer2);
      paramStgContext.R(2, localStgClosure2);
      Internal.zdwa4_closure.enter(paramStgContext);
      StgContext tmp160_159 = paramStgContext;
      tmp160_159;
      if (tmp160_159.checkForStackFrames(paramStgContext.stackTopIndex(), paramStgContext.stackTop())) {
        return;
      }
      localObject = paramStgContext.R(1);
      ((StgClosure)localObject).enter(paramStgContext);
    }
    else
    {
      Internal.satzusWF4 localsatzusWF4 = new Internal.satzusWF4(localByteBuffer1, localStgClosure1, i, j, localStgClosure2);
      n = i - 1;
      int i1 = n + 100;
      ByteBuffer localByteBuffer3 = (ByteBuffer)localByteBuffer1.duplicate().position(localByteBuffer1.position() + i1);
      int i3 = i - 1;
      localObject = (ByteBuffer)localByteBuffer1.duplicate().position(localByteBuffer1.position() + i3);
      paramStgContext.O(1, localObject);
      paramStgContext.O(2, localByteBuffer3);
      paramStgContext.R(2, localsatzusWF4);
      Internal.zdwa4_closure.enter(paramStgContext);
      StgContext tmp296_295 = paramStgContext;
      tmp296_295;
      if (tmp296_295.checkForStackFrames(paramStgContext.stackTopIndex(), paramStgContext.stackTop())) {
        return;
      }
      StgClosure localStgClosure3 = paramStgContext.R(1);
      localStgClosure3.enter(paramStgContext);
    }
  }
```
* would be `localByteBuffer1` `null`?

**Comment by rahulmutt** [comment]
You're right on target. The zdw prefix means this is the optimized, unboxed version of the original unpackAppendCharsLazy. Judging by the presence of extra code, it seems unpackAppendCharsStrict has been inlined and the change should be there. You'll need to add a null check there using isNullObject# from GHC.Base. See Java.Core for example of use. Since you have done a great job tracing the bug, you can go ahead an submit the fix. Let me know if need any other help from my side.

**Comment by jneira** [comment]
Mmm, but `nullAddr#` as java `null` could cause similar bugs in other modules/functions and they all would need null checks. Otoh I suppose the original ghc definition of `nullAddr#` doesnt make the bytestring code fail. 
Could eta translate `nullAddr#` to something that would not throw a NPE?, i dont know what can it be: an empty `ByteByffer`? a `ByteBuffer` with 0? some unique object Null?
(`nullAddr# is in the `GHC.Base` module but it is not as a standar module definition, i suppose it is translated by compiler magic, it's like this?)

**Comment by rahulmutt** [comment]
What we can do is create a static final ByteBuffer (in `eta.runtime.io.MemoryManager`) that we can import to the Eta side as an `Addr#` to populate `nullPtr` in `GHC.Ptr`. The main application of this is for sentinel values so equality of `Addr#` should be defined accordingly. Currently, equality for `Addr#` is defined in `ETA.CodeGen.Prim` in the `simpleOp AddrEqOp` case. Basically, it calls `eta.runtime.io.MemoryManager.getAddress` which returns `-1` if the `ByteBuffer` is null. Instead, we can create  bytebuffer that stores `-1` in its first 4 bytes whose position is at the end to simulate NULL and remove the case for `null`. Would you be interested in tackling this?

**Comment by rahulmutt** [comment]
The reason why it should be -1 is that 0 is the starting address for all memory allocated by the `MemoryManager` so it can cause some weird behaviour. We may even make it -2^(31), but that most likely won't make a difference.

**Comment by jneira** [comment]
Yeah, i'll try to implement the fix

**Comment by jneira** [comment]
Finally the solution seems to be change the translation of `__NULL` literal in stg code from java `null` to the constant `ByteBuffer` with address -1 (as commented above), in the bytecode generation phase. (thanks to @rahulmutt for point me the correct way to do it)

**Comment by rahulmutt** [comment]
@jneira Merged your PR, update and close if it works?

**Comment by jneira** [comment]
Yeah, the npe is solved

**Comment by rahulmutt** [comment]
Great, closing.
