### ISSUE TITLE
Implement File I/O primitives in base

### ISSUE THREAD

**Issue by basabuber** [typelead/eta#271]
This simple IO program (from RWH/bos) is giving an error:

module Main where

import           Data.Char (toUpper)
import           System.IO

main :: IO ()
main = do
  inh <- openFile "input.txt" ReadMode
  outh <- openFile "output.txt" WriteMode
  readWriteLoop inh outh
  hClose inh
  hClose outh

readWriteLoop :: Handle -> Handle -> IO ()
readWriteLoop inh outh = do
  inhEof <- hIsEOF inh
  if inhEof
    then return ()
    else do line <- hGetLine inh
            hPutStrLn outh (map toUpper line)
            readWriteLoop inh outh

**Comment by basabuber** [comment]
I am getting the following error:

epm run
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring eta-real-world-haskell-chapter7-io-0.1.0.0...
Warning: The 'license-file' field refers to the file 'LICENSE' which does not
exist.
Preprocessing executable 'eta-real-world-haskell-chapter7-io' for
eta-real-world-haskell-chapter7-io-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/eta-real-world-haskell-chapter7-io/eta-real-world-haskell-chapter7-io-tmp/Main.jar )
Linking dist/build/eta-real-world-haskell-chapter7-io/eta-real-world-haskell-chapter7-io.jar ...
Running eta-real-world-haskell-chapter7-io...
Prelude.undefined
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1333)
	at eta.runtime.RtsMessages.errorBelch(RtsMessages.java:32)
	at eta.base.Utils.errorBelch(Utils.java:183)
	at base.ghc.conc.Sync$satzusELPB.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD2TO.enter(Unknown Source)
	at base.ghc.Foreign$satzusD2UF.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$satzusELPC.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD2TO.enter(Unknown Source)
	at base.ghc.Foreign$satzusD2UF.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$zdLrELKTlvl6.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at base.ghc.TopHandler$satzusI946.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)

Is this a reproducible error?

**Comment by rahulmutt** [comment]
Basically, File I/O has not been implemented yet. It will be done before the first release. Will make this issue track it.

**Comment by basabuber** [comment]
Ah :).

**Comment by corporatepiyush** [comment]
Will File IO be based on blocking IO or Non-blocking IO ?
I am hoping that adopting nio2 package will be more useful for green thread concurrency.
Is there any roadmap for first release ?

**Comment by Abhiroop** [comment]
You can find the milestones for the first release here: https://github.com/typelead/eta/milestone/1 And we are indeed going ahead with non blocking IO. Pending issues in concurrency are here: https://github.com/typelead/eta/labels/concurrent
