### ISSUE TITLE
QuickCheck crashes

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#277]
```haskell
import Control.Monad
import Test.QuickCheck
import Test.QuickCheck.Test
import System.Exit

prop_revapp :: [Int] -> [Int] -> Bool
prop_revapp xs ys = reverse (xs++ys) == reverse xs ++ reverse ys

main :: IO ()
main = do
  result <- quickCheckResult prop_revapp
  unless (isSuccess result) exitFailure
  print result
```

```
Exception in thread "main" java.lang.ClassCastException: ghc_prim.ghc.Tuple$Z2TD cannot be cast to quickcheck.test.quickcheck.Test$SuccessD
	at quickcheck.test.quickcheck.Test$zdwzdcshowsPrec1.enter(Unknown Source)
	at main.Main$satzusLB3.enter(Unknown Source)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main9.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```

**Comment by twoquarterrican** [comment]
I don't know if this adds anything, but I am having similar issues with QuickCheck.  My repo is here:
https://github.com/twoquarterrican/eta-first

If it helps.  I can run `stack test` and everything works just fine.  `etlas run` also behaves as expected.

here is the main test code:

```
module Main where

import ListGen
import Test.QuickCheck
import System.Random
import Data.List

main = quickCheck prop_size

prop_size (Positive n) seed = n == length (distinct (mkStdGen seed) (n+1) n)
prop_distinct uBound n seed = nub generated == generated where
  generated = distinct (mkStdGen seed) uBound n
```
here is the result of running `etlas test`

```
$ etlas testPreprocessing test suite 'tests' for eta-first-0.1.0.0..
Building test suite 'tests' for eta-first-0.1.0.0..
Running 1 test suites...
Test suite tests: RUNNING...
Exception in thread "main" java.lang.ClassCastException: [J cannot be cast to [Ljava.lang.Object;
	at base.java.Array$zdfJavaConverterZMZNczuzdcfromJava.enter(Unknown Source)
	at tf_random.system.random.tf.Gen$satzusWVM.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at tf_random.system.random.tf.Gen$zdwmash.enter(Unknown Source)
	at tf_random.system.random.tf.Gen$satzusWZZY.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at quickcheck.test.quickcheck.Random$zdfRandomGenQCGenzuzdcnext.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:116)
	at eta.runtime.apply.ApP.stackEnter(ApP.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at random.system.Random$zdwf2zus1G43.enter(Unknown Source)
	at random.system.Random$zdwrandomIvalInteger.enter(Unknown Source)
	at quickcheck.test.quickcheck.Arbitrary$satzus2JAJ.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.Apply$ApPPFast.enter(Apply.java:125)
	at quickcheck.test.quickcheck.Gen$xzusRLN.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at integer.ghc.integer.Type$integerToInt.enter(Unknown Source)
	at quickcheck.test.quickcheck.Arbitrary$zdfArbitraryInt2.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:116)
	at eta.runtime.apply.Apply$ApPFast.enter(Apply.java:96)
	at quickcheck.test.quickcheck.Gen$zdwa2.enter(Unknown Source)
	at quickcheck.test.quickcheck.Gen$zdwa1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Arbitrary$zdwa10.enter(Unknown Source)
	at quickcheck.test.quickcheck.Arbitrary$zdfArbitraryInt1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.ApPP.stackEnter(ApPP.java:19)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at ghc_prim.ghc.Classes$neInt.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.ApPP.stackEnter(ApPP.java:19)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at quickcheck.test.quickcheck.Gen$zdwa2.enter(Unknown Source)
	at quickcheck.test.quickcheck.Gen$zdwa1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Modifiers$satzus3D4G.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.Num$zdfNumIntzuzdcabs.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:116)
	at eta.runtime.apply.ApP.stackEnter(ApP.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at ghc_prim.ghc.Classes$gtInt.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.ApPP.stackEnter(ApPP.java:19)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at quickcheck.test.quickcheck.Gen$zdwa2.enter(Unknown Source)
	at quickcheck.test.quickcheck.Gen$zdwa1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Modifiers$satzus3D4N.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:189)
	at eta.runtime.apply.ApPP.stackEnter(ApPP.java:19)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at main.Main$propzusizze.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:148)
	at eta.runtime.apply.ApP.stackEnter(ApP.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at quickcheck.test.quickcheck.Property$satzus41FT.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at quickcheck.test.quickcheck.Property$satzus41B8.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at quickcheck.test.quickcheck.Property$satzus41BI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41CM.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41CM.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$satzus41GI.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at quickcheck.test.quickcheck.Property$reduceRose1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Property$reduceRose1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Property$reduceRose1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Property$reduceRose1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Property$reduceRose1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Test$satzus4P0Q.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at quickcheck.test.quickcheck.Test$zdwa8.enter(Unknown Source)
	at quickcheck.test.quickcheck.Test$zdwa9.enter(Unknown Source)
	at quickcheck.test.quickcheck.Test$satzus4PGO.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at quickcheck.test.quickcheck.Text$satzusXAE.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$UnmaskAsyncExceptions.enter(StgException.java:144)
	at base.control.exception.Base$satzusFJ0J.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at base.control.exception.Base$satzusFJ0W.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$MaskAsyncExceptions.enter(StgException.java:75)
	at base.control.exception.Base$finally1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Text$withStdioTerminal1.enter(Unknown Source)
	at quickcheck.test.quickcheck.Test$zdwa7.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main6.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
Test suite tests: FAIL
Test suite logged to: dist/test/eta-first-0.1.0.0-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

**Comment by rahulmutt** [comment]
Can you try again after running `./update.sh`? There was a change that should've fixed this.

**Comment by twoquarterrican** [comment]
yup, works now. thanks!

**Comment by rahulmutt** [comment]
This appears to be fixed on `master`.
