### ISSUE TITLE
exitSuccess crashes

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#278]
```haskell
main = exitSuccess
```

```
Running eta-test...
user error (If you can read this, shutdownHaskellAndExit did not exit.)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1333)
	at eta.runtime.RtsMessages.errorBelch(RtsMessages.java:32)
	at eta.base.Utils.errorBelch(Utils.java:183)
	at base.ghc.conc.Sync$satzusES4R.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD6T2.enter(Unknown Source)
	at base.ghc.Foreign$satzusD6TT.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$satzusES4S.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD6T2.enter(Unknown Source)
	at base.ghc.Foreign$satzusD6TT.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$zdLrES09lvl6.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at base.ghc.TopHandler$satzusI9AW.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Fixed as of d1ee89f6e7548da1c18e5d1a03a815a06867acd2
