### ISSUE TITLE
How to run eta's jar by Java command

### ISSUE THREAD

**Issue by JulianZhang** [typelead/eta#316]
Dear all, I need run the jar on the server which unable install eta and etlas. 

So I want to know how to run eta's jar by Java command, How can I know which jars I need including to class path.

```
$ etlas run
Preprocessing executable 'eta-example' for eta-example-0.1.0.0..
Building executable 'eta-example' for eta-example-0.1.0.0..
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/eta-example/eta-example-tmp/Main.jar )
Linking dist/build/eta-example/eta-example.jar ...
Running eta-example...
eta hello

$ java -jar dist/build/eta-example/eta-example.jar
Exception in thread "main" java.lang.NoClassDefFoundError: eta/runtime/RtsConfig
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.runtime.RtsConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by rahulmutt** [comment]
Check the `dist/build/eta-example/eta-example`. It'll be a bash script that calls `java` with the full classpath containing all the libraries. If you want to build a standalone jar, run the following commands in your project:

```
etlas clean
etlas configure --enable-uberjar-mode # Needs to be done once
etlas build # You will now have an uberjar 
```

**Comment by JulianZhang** [comment]
Thanks , it fix my problem.
