### ISSUE TITLE
Get error when use option package 

### ISSUE THREAD

**Issue by JulianZhang** [typelead/eta#317]
Dear all, I use option package in Main.hs as blow 

```
{-# LANGUAGE MagicHash #-}

import Control.Applicative
import Options

data MainOptions = MainOptions
	{ port :: Int
	, message :: String
	}

instance Options MainOptions where
    	defineOptions = pure MainOptions
    		<*> simpleOption "port" 8088
    		    "the port for web service "
    		<*> simpleOption "message" "test message"
    		    "message for testing."

main :: IO ()
main = runCommand $ \opts args -> do
		putStrLn (message opts)
```

I can use package to get options, But if I input --help or -h will get a error 

```
$etlas run -- -h
Preprocessing executable 'eta-example' for eta-example-0.1.0.0..
Building executable 'eta-example' for eta-example-0.1.0.0..
注: java/Word2VecRawText.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Running eta-example...
Help Options:
  -h, --help
    Show option summary.
  --help-all
    Show all help options.

Application Options:
  --port :: int
    the port for web service
    default: 8088
  --message :: text
    message for testing.
    default: "test message"
user error (If you can read this, shutdownHaskellAndExit did not exit.)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at eta.runtime.RtsMessages.errorBelch(RtsMessages.java:32)
	at eta.base.Utils.errorBelch(Utils.java:183)
	at base.ghc.conc.Sync$satzusES4R.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD6T2.enter(Unknown Source)
	at base.ghc.Foreign$satzusD6TT.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$satzusES4S.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Foreign$zdwa1.enter(Unknown Source)
	at base.ghc.Foreign$zdwa4zusD6T2.enter(Unknown Source)
	at base.ghc.Foreign$satzusD6TT.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at base.ghc.conc.Sync$zdLrES09lvl6.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at base.ghc.TopHandler$satzusI9AW.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```

I had try to build project with stack use lts-6.31. And the error will not show 

```
$.stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/eta-example/eta-example --help
Help Options:
  -h, --help
    Show option summary.
  --help-all
    Show all help options.

Application Options:
  --port :: int
    the port for web service
    default: 8088
  --message :: text
    message for testing.
    default: "test message"
$
```

**Comment by rahulmutt** [comment]
This looks related to #278, given that the program gives the correct output, but fails at the very end. I'll take a look since this is coming up frequently

**Comment by rahulmutt** [comment]
Can you try running `./update.sh` in your local clone? I pushed something that may fix this.

**Comment by JulianZhang** [comment]
@rahulmutt after update, I can't build project now 

```
$etlas build
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: eta-example-0.1.0.0 (user goal)
unknown package: base (dependency of eta-example-0.1.0.0)
fail (backjumping, conflict set: base, eta-example)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: eta-example, base
Trying configure anyway.
Configuring eta-example-0.1.0.0...
etlas: Encountered missing dependencies:
base -any, hjson -any, options -any
zhangjuns-MacBook-Pro:eta-example zhangjun$ etlas install base hjson options
Resolving dependencies...
etlas: Could not resolve dependencies:
next goal: base (user goal)
rejecting: base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0 (only already installed instances can be used)
rejecting: base-3.0.3.2, base-3.0.3.1 (conflict: base => base>=4.0)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base

```

**Comment by JulianZhang** [comment]
Dear @rahulmutt , after update, it didn't fix the problem.

**Comment by rahulmutt** [comment]
@JulianZhang Try running `./cleaninstall.sh` and try again? I am unable to reproduce the exception on the most recent commit.

**Comment by JulianZhang** [comment]
This problem is fix with 0.0.6b3 on centos, I will check on mac later.

**Comment by rahulmutt** [comment]
@JulianZhang Have you had a chance to check this on your mac? After the last patch this should be fixed. Please close if so.

**Comment by JulianZhang** [comment]
fix now.
