### ISSUE TITLE
IncompatibleClassChangeError Using FFI for OkHttp

### ISSUE THREAD

**Issue by twoquarterrican** [typelead/eta#359]
I am pretty sure I am doing something wrong here, but I can't figure it out.  I finally got the code below to compile, but now when I run it, I get
```
Running http-client-examples...
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface okhttp3.Call, but class was expected
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main3.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:95)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
```
Here is the code from Main.hs
```
{-# LANGUAGE MagicHash #-}

module Main(main) where

import Java

data {-# CLASS "okhttp3.OkHttpClient" #-} OkHttpClient = OkHttpClient (Object# OkHttpClient)
  deriving Class
data {-# CLASS "okhttp3.Request" #-} Request = Request (Object# Request)
  deriving Class
data {-# CLASS "okhttp3.Response" #-} Response = Response (Object# Response)
  deriving Class
data {-# CLASS "okhttp3.Request$Builder" #-} RequestBuilder = RequestBuilder (Object# RequestBuilder)
  deriving Class
data {-# CLASS "okhttp3.Call" #-} Call = Call (Object# Call)
  deriving Class
data {-# CLASS "okhttp3.ResponseBody" #-} ResponseBody = ResponseBody (Object# ResponseBody)
  deriving (Class, Show)

foreign import java unsafe "@new" newOkHttpClient :: Java a OkHttpClient
foreign import java unsafe "@new" newRequestBuilder :: Java a RequestBuilder
foreign import java unsafe url :: String -> Java RequestBuilder RequestBuilder
foreign import java unsafe build :: Java RequestBuilder Request
foreign import java unsafe newCall :: Request -> Java OkHttpClient Call
foreign import java unsafe execute :: Java Call Response
foreign import java unsafe body :: Java Response ResponseBody

main :: IO ()
main = do
    iorespbody <- java $ do
        client <- newOkHttpClient
        request <- newRequestBuilder >- (url "https://raw.github.com/square/okhttp/master/README.md") >- build
        response <- client <.> (newCall request) >- execute
        response <.> body
    putStrLn $ show iorespbody
```
Here is the relevant bit of my cabal file:
```
executable http-client-examples
  -- .hs or .lhs file containing the Main module.
  main-is:             Main.hs
  
  -- Modules included in this executable, other than Main.
  -- other-modules:       
  
  -- LANGUAGE extensions used by modules in this package.
  -- other-extensions:    
  
  -- Other library packages from which modules are imported.
  build-depends:       base >=4.8 && <4.9

  maven-depends:       com.squareup.okhttp3:okhttp:3.7.0
  
  -- Directories containing source files.
  hs-source-dirs:      src
  
  -- Base language which the package is written in.
  default-language:    Haskell2010
```
My goal is here is learning.  I am just trying to learn eta-java interop by running the sample code (given in java) from here: https://raw.githubusercontent.com/square/okhttp/master/samples/guide/src/main/java/okhttp3/guide/GetExample.java

**Comment by rahulmutt** [comment]
Perhaps you meant this?
```haskell
foreign import java unsafe "@inteface" execute :: Java Call Response
```
(Since `Call` looks to be an interface, that's what the JVM is telling you in a very cryptic way.)

Getting better compile-time verification is in the works, see #217.

**Comment by rahulmutt** [comment]
There was a typo above, fixed.

**Comment by twoquarterrican** [comment]
Thanks! I see that now in the docs http://eta-lang.org/docs/html/eta-tutorials.html#working-with-covariance-and-contravariance
missed it the first time because I wasn't ready to start thinking about covariance and contravariance :)
