### ISSUE TITLE
Calling Data.ByteString.readFile causes java.lang.ClassCastException

### ISSUE THREAD

**Issue by jonathanknowles** [typelead/eta#398]
## Summary

Attempting to call the function [`Data.ByteString.readFile`](https://hackage.haskell.org/package/bytestring/docs/Data-ByteString.html#v:readFile) (from the popular [ByteString](https://hackage.haskell.org/package/bytestring) library) causes a `java.lang.ClassCastException` to be thrown.

## Environment

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
```
$ uname -a
Linux helium 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ stack --version
Version 1.4.0, Git revision 5986498a9d1073e8d58c79ec1302bb2a7847a396 (4642 commits) x86_64 hpack-0.17.0
```
```
$ eta --version
Compiler for the Eta Programming Language, version 0.0.6b7
```
```
$ etlas --version
etlas version 1.0.0.0
compiled using version 2.1.0.0 of the etlas-cabal library 
```

## Reproduction steps

Clone the following sample project:
```
$ git clone https://github.com/jonathanknowles/bytestring-readfile-example
$ cd bytestring-readfile-example
```
Observe that the project builds successfully with GHC:
```
$ stack setup
$ stack build
bytestring-readfile-example-0.1.0.0: configure (exe)
Configuring bytestring-readfile-example-0.1.0.0...
bytestring-readfile-example-0.1.0.0: build (exe)
Preprocessing executable 'bytestring-readfile-example' for
bytestring-readfile-example-0.1.0.0...
[1 of 1] Compiling Main             ( source/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/bytestring-readfile-example/bytestring-readfile-example-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/bytestring-readfile-example/bytestring-readfile-example ...
bytestring-readfile-example-0.1.0.0: copy/register
Installing executable(s) in
/home/user/bytestring-readfile-example/.stack-work/install/x86_64-linux/lts-6.27/7.10.3/bin
```
Observe that the project also builds successfully with Eta:
```
$ etlas build
Resolving dependencies...
Configuring bytestring-readfile-example-0.1.0.0...
Preprocessing executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
Building executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
[1 of 1] Compiling Main             ( source/Main.hs, dist/build/bytestring-readfile-example/bytestring-readfile-example-tmp/Main.jar )
Linking dist/build/bytestring-readfile-example/bytestring-readfile-example.jar ...
```
For testing purposes, first write a small amount of data to a temporary file:
```
$ dd if=/dev/urandom of=/tmp/foo bs=256 count=1
```
Observe that the GHC build runs correctly:
```
$ stack build
stack build took 317ms
$ stack exec bytestring-readfile-example  
Please enter a valid file path:
/tmp/foo
Number of bytes read:
256
```
Now attempt to run the Eta build:
```
$ etlas run
Preprocessing executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
Building executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
Running bytestring-readfile-example...
Please enter a valid file path:
/tmp/foo
```

## Expected behaviour

The Eta build produces the same output as the GHC build.

## Actual behaviour

The runtime reports a ClassCastException:
```
$ etlas run
Preprocessing executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
Building executable 'bytestring-readfile-example' for bytestring-readfile-example-0.1.0.0..
Running bytestring-readfile-example...
Please enter a valid file path:
/tmp/foo
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.nio.file.attribute.FileAttribute;
	at base.system.posix.Types$DFileAttributeArray.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:99)
	at eta.runtime.apply.ApO.stackEnter(ApO.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.system.posix.Types$zdfClassFileAttributeArrayzuzdcunobj.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:116)
	at eta.runtime.apply.ApP.stackEnter(ApP.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.java.Array$satzusLN2I.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:99)
	at eta.runtime.apply.ApO.stackEnter(ApO.java:17)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.system.posix.Internals$czuopen1.enter(Unknown Source)
	at base.ghc.io.handle.FD$satzusIG1F.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at base.ghc.io.handle.FD$openBinaryFile1.enter(Unknown Source)
	at main.Main$satzusC02.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.control.exception.Base$satzusFO5J.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$MaskAsyncExceptions.enter(StgException.java:75)
	at base.control.exception.Base$bracket1.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main4.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:264)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:98)
	at eta.runtime.Rts.hsMain(Rts.java:40)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
This is related to #271. Once File I/O primitives are implemented (should be done soon), this will work fine. In the mean time, you can do foreign imports of `java.io.File`,`FileInputStream`, etc. to do the file reading/writing.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt
Thank-you for your reply and explanation.
I will use foreign imports for now, as you suggest. :+1: 
All the best
Jonathan

**Comment by jonathanknowles** [comment]
In the spirit of the advice above (to use foreign imports), I used a foreign import of function [`java.nio.file.Files.readAllBytes`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAllBytes(java.nio.file.Path)) to read the content of my file into memory. (See: https://github.com/jonathanknowles/eta-readfile-example/blob/master/source/Main.hs)

The resulting value is of type `JByteArray`.

@rahulmutt is there a supported way to convert from `JByteArray` to a strict `Data.ByteString`? My aim is to reuse a large existing Haskell library that works with values of type `ByteString`.

Thanks again!

**Comment by rahulmutt** [comment]
Yes. There's a `fromJava` function you can use.

```haskell
import Data.ByteString

toByteString :: JByteArray -> ByteString
toByteString jbytes = B.pack word8s
  where word8s = map fromIntegral (fromJava bytes :: [Byte])
```

**Comment by jonathanknowles** [comment]
Ah yes that makes sense. Thanks for this suggestion.

I've updated my example code, here: https://github.com/jonathanknowles/eta-readfile-example/blob/master/source/Main.hs

Many thanks!
Jonathan

**Comment by rahulmutt** [comment]
Looks good! When you're finished with it, please send a PR to the [eta-examples](https://github.com/typelead/eta-examples) repo and we can add it to the listing in the README.

**Comment by jonathanknowles** [comment]
Thanks @rahulmutt

I ran a few experiments, and it seems that this approach seems to break down (unfortunately) when converting arrays larger than a few KiB.

For example: converting a 2048-byte long `JByteArray` to a `ByteString` works as expected:
```
$ dd if=/dev/urandom of=/tmp/foo bs=2048 count=1
1+0 records in
1+0 records out
2048 bytes (2.0 kB, 2.0 KiB) copied, 0.00089696 s, 2.3 MB/s
$ etlas run
Preprocessing executable 'eta-readfile-example' for eta-readfile-example-0.1.0.0..
Building executable 'eta-readfile-example' for eta-readfile-example-0.1.0.0..
Running eta-readfile-example...
Please enter a valid file URI: file:///tmp/foo
Reading file contents into memory: done
Number of bytes read: 2048
Converting from JByteArray to ByteString: done
Number of bytes converted: 2048
```
But make the array just a bit larger (8192 bytes), and we run out of stack space:
```
$ dd if=/dev/urandom of=/tmp/foo bs=8192 count=1
1+0 records in
1+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.00171715 s, 4.8 MB/s
$ etlas run
Preprocessing executable 'eta-readfile-example' for eta-readfile-example-0.1.0.0..
Building executable 'eta-readfile-example' for eta-readfile-example-0.1.0.0..
Running eta-readfile-example...
Please enter a valid file URI: file:///tmp/foo                               
Reading file contents into memory: done
Number of bytes read: 8192
Converting from JByteArray to ByteString: done
Number of bytes converted: Exception in thread "main" java.lang.StackOverflowError
	at eta.runtime.apply.StgFun.apply(StgFun.java:113)
	at eta.runtime.apply.Apply$ApPFast.enter(Apply.java:96)
	at eta.runtime.thunk.Ap2Upd.thunkEnter(Ap2Upd.java:21)
	at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
	at bytestring.data.bytestring.Internal$zdwa.enter(Unknown Source)
        ...
```
(source: https://github.com/jonathanknowles/eta-readfile-example/blob/2e50767d5978cda6cf2fc3d6a236d1f4cc2ff73c/source/Main.hs)

In your opinion, is this a bug?

I'm guessing it would be nice if there were some way to avoid using lists as an intermediate representation (unless this can be optimised away using fusion rules). Perhaps there is a nicer way to perform the conversion. (It would be really convenient, for example, if the in-memory representation of a `JByteArray` and a `ByteString` were the same, then perhaps we could just do a `memcpy` -- not sure if this is possible in the JVM world).

Cheers
Jonathan

**Comment by rahulmutt** [comment]
Thanks for checking out the perf! We're still actively working on it. 

There's one bit to this particular problem though, that we can take a look at: the intermediate `Word8` and `Byte` lists. 

The faster way to do this would be to:

1. Take the `ByteBuffer` which is a pointer to native, off-heap memory that underlies the `ForeignPtr` of `ByteString.
2. Send it to a Java method that takes a `ByteBuffer` and `byte[]` and use [ByteBuffer.put](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#put(byte[])) which is the closest you can get to `memcpy` on the JVM.

If you're interested in trying this out, I'd be happy to help you through the implementation, in which case we can update the patch `bytestring` to provide a `fromJava` instance for directly converting `JByteArray` to `ByteString`.

**Comment by rahulmutt** [comment]
Regarding the `StackOverflowError` you got, can you post that as a separate issue with the exact program/parameters you used to run it? There are some optimisations we can do there we haven't gotten around to yet and it would be nice to have a test case to make sure the optimisations worked once we get around to implementing them.

**Comment by rahulmutt** [comment]
`StackOverflowErrors` may be an indication of a space leak. That `zdwa.enter()` chain you see is the runtime string to evaluate a nested thunk (like a giant lazy list).

Eta is a *lot* more sensitive to space leaks than GHC since we use the JVM stack instead of our own to implement the STG evaluation model. GHC on the other hand uses infinite stack size, so it can keep on going as long as you have enough heap space.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt 

As suggested, I've created an separate issue (issue #401) for the `StackOverflowError`, along with a very simple program that triggers the error. Hopefully the issue can be reproduced, but let me know if not. :)

Cheers
Jonathan

**Comment by rahulmutt** [comment]
@jonathanknowles, thanks for creating the issue :) I'll see if I can look into the direct conversion method at some point - I'd imagine that conversion will be extremely common when trying to merge the JVM/Haskell ecosystems.

**Comment by rahulmutt** [comment]
All the issues in this thread were resolved, closing.
