### ISSUE TITLE
Evaluation of Data.ByteString.unfoldrN blows up with java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by jonathanknowles** [typelead/eta#408]
## Environment

```
$ eta --version
Compiler for the Eta Programming Language, version 0.0.6b7
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

## Reproduction

Consider the following function defined in terms of [`Data.ByteString.unfoldrN`](https://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString.html#v:unfoldrN), which simulates the behaviour of [`Data.ByteString.replicate`](https://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString.html#v:replicate):

```haskell
replicate' :: Int -> Word8 -> ByteString
replicate' n c = fst $ B.unfoldrN n (const $ Just (c, c)) c
```
With GHC, evaluation of `replicate' n c` completes within a relatively short space of time (even for relatively high values of `n`):  ([source](https://github.com/jonathanknowles/eta-memory-usage/blob/20d330deaec5e383b3e6049ef703ecd4e84302bd/source/Main.hs))
```
      n:length (MiB)   a:replicate  (μs)   b:replicate' (μs)     b/a
                   2                 294               2,678       9
                   4                 816               4,416       5
                   6               1,516               7,420       4
                   8               1,802              10,522       5
                  10               6,179              11,456       1
                  12               2,504              14,590       5
                  14               8,750              18,661       2
                  16              11,791              17,405       1
                  18               6,521              20,104       3
                  20               4,464              29,638       6
                  22               4,964              25,524       5
                  24               5,332              28,043       5
                  26               5,889              35,527       6
                  28               6,223              31,412       5
                  30              10,521              33,475       3
                  32               7,294              35,101       4
                  34               8,322              37,442       4
                  36               6,389              39,444       6
                  38               8,528              42,561       4
                  40               9,384              43,353       4
                  42               9,405              45,660       4
                  44              21,544              46,019       2
                  46              10,842              49,632       4
                  48               8,016              51,767       6
                  50              11,371              54,296       4
                  52              12,037              55,644       4
                  54              12,548              57,786       4
                  56              13,264              59,742       4
                  58              13,797              61,917       4
                  60              14,329              64,056       4
                  62              14,414              66,212       4
                  64              14,945              68,379       4
```
But with Eta, evaluation blows up with an OutOfMemoryError, even for relatively small values of `n`.
```
      n:length (MiB)   a:replicate  (μs)   b:replicate' (μs)     b/a
                   2              39,000           1,843,000      47
                   4              41,000           2,010,000      49
                   6               7,000           2,563,000     366
                   8              13,000           7,163,000     551
                  10              49,000           8,308,000     169
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.nio.DirectByteBuffer.duplicate(DirectByteBuffer.java:217)
	at main.Main$satzus15H1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:138)
	at eta.runtime.apply.Apply$ApPVFast.enter(Apply.java:105)
	at bytestring.data.bytestring.Internal$zdwa2.enter(Unknown Source)
	at main.Main$satzus15H2.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at main.Main$zdwcreateByteStringWithUnfoldrN.enter(Unknown Source)
	at main.Main$main3.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:264)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:98)
	at eta.runtime.Rts.hsMain(Rts.java:40)
	at eta.main.main(Unknown Source)
```
Examining the [source for `unfoldrN`](https://hackage.haskell.org/package/bytestring-0.10.8.1/docs/src/Data-ByteString.html#unfoldrN) reveals that it constructs a `ByteString` by repeatedly calling [`poke`](https://hackage.haskell.org/package/base-4.9.1.0/docs/Foreign-Storable.html#v:poke) within a loop that attempts to be strict in its accumulator arguments:
```haskell
unfoldrN :: Int -> (a -> Maybe (Word8, a)) -> a -> (ByteString, Maybe a)
unfoldrN i f x0
    | i < 0     = (empty, Just x0)
    | otherwise = unsafePerformIO $ createAndTrim' i $ \p -> go p x0 0
  where
    go !p !x !n
      | n == i    = return (0, n, Just x)
      | otherwise = case f x of
                      Nothing     -> return (0, n, Nothing)
                      Just (w,x') -> do poke p w
                                        go (p `plusPtr` 1) x' (n+1)
```
Perhaps something is preventing the Eta compiler from optimising this into a loop (with constant memory usage)?

**Comment by rahulmutt** [comment]
Thanks for doing these benchmarks, really helps to see where we need to improve!

I'm willing to bet that the Eta compiler *is* optimising this as a loop, but there is another factor in play that is killing the performance:
- `plusPtr` is cheap in GHC - it's equivalent to a machine integer addition. In Eta, it's expensive - it creates a new ByteBuffer object, so on the scale of MBs, you'll for sure be creating ~10^6 ByteBuffer objects - this amount of allocation will be sure to stress the GC. This bit hints at this reason:

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.nio.DirectByteBuffer.duplicate(DirectByteBuffer.java:217)
```

This was done to maintain purity but it seems to be killing performance. We'll need to look at a more efficient way of implementing pointer arithmetic in Eta and this benchmark will be a great measuring stick. 

This may mean we need to rethink the `bytestring` implementation in Eta given the hard limits we have on the JVM (no direct access to an absolute pointer address with fast fetches). Especially in the internal representation and how it's operated on - probably better to use a byte array instead of allocating off-heap memory like it does now.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt 

Thanks for getting back to me. This explanation makes sense.

I'm curious about the implementation of `plusPtr` you mention: would you be able to point me toward Eta's implementation of this? 

Thanks!

Jonathan

**Comment by rahulmutt** [comment]
So if you ever want to trace the implementation of a low-level operation (taking `plusPtr` in this case):

1. Grep for `^plusPtr` in the `libraries` sub-directory of the codebase, you'll find that it's `GHC.Ptr` in `base`:
```
plusPtr :: Ptr a -> Int -> Ptr b
plusPtr (Ptr addr) (I# d) = Ptr (plusAddr# addr d)
```
2. Now keep chasing the definitions of the functions used in the implementation. In this case, you will not be able to trace `plusAddr#` since it's a primitive operation that gets directly generated by the codegen. (You can tell it's a primitive operation since it has a `#` at the end.)
3. Grep for `plusAddr#` and you should find one result that begins with `primOpInfo` followed by a data constructor of the form `*Op`, in this case `AddrAddOp`.
4. Go to `ETA.CodeGen.Prim` and search for the data constructor you found in (3), and you'll find the implementation. It requires rudimentary understanding of JVM bytecode.

I'll add the above steps in the developer docs.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt

Just wondering if you've had any further thoughts on how to tackle the pointer arithmetic problem?

I've been giving the problem some thought, and had a few ideas that I thought would be worth sharing with you. (Apologies if you've already thought of a similar solution, or if there is an obvious reason why this solution wouldn't work!)

Given current JVM limitations, it seems that any object-based representation of pointers is bound to run into similar performance issues (even if the object only has one field).

What if, instead of using a `ByteBuffer` object to encode a pointer, we instead use a 64-bit `long` value, where:

 * the most-significant half (bits 63 ... 32) encodes a `int` key that uniquely identifies a byte array.
 * the least-significant half (bits 31 ... 0) encodes an `int` index into the given byte array.

Then, we can **construct** a pointer with the following function:
```Java
long makePtr (final int key, final int index) {
    return (((long) key) <<< 32) & ((long) indexNew);
}
```
We can **deconstruct** a pointer with the following pair of functions:
```Java
int ptrKey (final long ptr) {
    return (int) ptr >>> 32;
}

int ptrIndex (final long ptr) {
    return (int) ptr & Integer.MAX_VALUE;
}
```
On **initialisation** of a new byte array (represented by an object of type `ByteArray`), we assign it a unique key (of type `int`), and store a `WeakReference` to it in a map:
```Java
Map <Integer, WeakReference <ByteArray>> arrayMap = ...
```
(this seems somewhat similar to the current implementation of [`eta.runtime.io.MemoryManager`](https://github.com/typelead/eta/blob/3fe69f67fef5580136e66a9bfda69e672b76b442/rts/src/eta/runtime/io/MemoryManager.java).)

Now, when we want to perform **pointer arithmetic**, we can use simple primitive addition operations to encode the ``ptr `plusPtr` off`` operation (taking care in case of overflow, to avoid indexing into the wrong array):

```Java
long plusPtr (final long ptr, final int off) {
    return makePtr (ptrKey (ptr), ptrIndex (ptr) + off);
}

long minusPtr (final long ptrA, final long ptrB) {
    // We probably need to insist that ptrKey (ptrA) == ptrKey (ptrB)
    return makePtr (ptrKey (ptrA), ptrIndex (ptrB) - ptrIndex (ptrA));
}
```
We can encode **`peek`** and **`poke`** operations with functions similar to:
```Java
byte peek (final long ptr) {
    final ByteArray array = arrayMap.get (ptrKey (ptr));
    if (array == null) {
        // Do something clever if the key doesn't refer to anything.
    } else {
        // Do something clever if the index is out-of-bounds.
        return array.get (ptrIndex (ptr));
    }
}

void poke (final long ptr, final byte value) {
    final ByteArray array = arrayMap.get (ptrKey (ptr));
    if (array == null) {
        // Do something clever if the key doesn't refer to anything.
    } else {
        // Do something clever if the index is out-of-bounds.
        array.set (ptrIndex (ptr), value);
    }
}
```
In your opinion, does this approach seem viable?

All the best

Jonathan

**Comment by rahulmutt** [comment]
When contemplating this problem last week, I arrived at the same conclusion as you did: use a `long` to represent and `Addr#` and the design I had in mind looks *very* similar to what you've provided above - thanks for taking the time to do a writeup!

I completely agree with what you wrote above - would you be interested in taking a stab at this? I can provide an assist on any bits of the implementation that you may have trouble with and provide an outline for which parts of the code generator/runtime system will require changes and what needs to be done.

The current implementation of `MemoryManager` is incredibly naive and doesn't do any "freeing" of the address space so it's easy to easy to reach the 2GB limit of the current address space. Moreover, it takes advantage of the fact that the memory allocated by a `ByteBuffer` will free up when the `ByteBuffer` object itself is GC'd. At the time I just wanted an initial implementation to demonstrate that the `bytestring` library can yield the *correct* results without any code changes to the library itself (beyond C FFI). 

My main concern with the proposal above is this bit:

```java
arrayMap.get (ptrKey (ptr));
```

This operation will be *extremely* frequent, especially in the benchmark above, so in the implementation of `get`, we need a fast path that will cache the most recent access(es) and return the ByteArray immediately if the new access key(s) is the same as the last one(s). This may require you to implement a custom Map implementation that overrides the `get` method and `put` methods.

In terms of lifecycle, don't worry about it. Finishing up the implementation of `WeakPtr`'s and finalisers will take care of making sure that the memory spaces get cleaned up (will file an issue shortly). And then we'll need to add a recurring background task in the runtime that will freeze the arrayMap and do some form of compaction. There are many ways to play with this with various tradeoffs in perf. Thoughts on this?

**Comment by jonathanknowles** [comment]
Hi @rahulmutt

I would be interesting in taking a look at implementing this. (I will probably need to balance the time a bit with other projects, but if you are okay with that, then I'm happy to proceed. On the other hand, if the implementation is time-sensitive, then let me know.)

Thanks for offering to provide an outline for which parts of the code generator/runtime system might require changes: that would be very helpful!

I do share your concerns about the performance of this:

```Java
arrayMap.get (ptrKey (ptr));
```

I like the idea of providing a fast path (that caches the most recent access(es)). It seems reasonable that this should help with the common use case of constructing a `ByteString` by repeatedly calling `poke` within a loop (as is the case with `unfoldrN`). Having a good set of benchmarks will be valuable here!

I'm also interested in the problem of what will happen to performance of our hypothetical memory manager in the context of multiple threads. I notice that the current implementation of [`MemoryManager`](https://github.com/typelead/eta/blob/3fe69f67fef5580136e66a9bfda69e672b76b442/rts/src/eta/runtime/io/MemoryManager.java) takes the approach of synchronizing public operations that read and write to the inner `addressMap` object.

I'm guessing that to start with, we can continue to use a similar approach of synchronizing access (for simplicity) to our hypothetical address map. If, later on, this proves to be a bottleneck, then perhaps (when we have enough time) we can consider moving to a data structure that allows for greater levels of concurrency. So in other words: prioritise safety first, and then optimise for performance later. Does this approach sound sensible?

Jonathan

**Comment by rahulmutt** [comment]
Sure. As of now this is not time-critical, but I'll let you know if priorities change.

I think the best way to go about this is for you to create a WIP (Work In Progress) pull request which you push to every time you want some review from my side. That way, if at any time the priorities change and we need this right away, we can rebase our changes starting with whatever you've done and finish up any remaining work. When we merge to master, you'll get proper credit for even partial work that you've done.

The outline will take some time - I'll try to post it within the next couple days in an entirely separate issue that takes into account the points you brought up as well. On top of that, I'll start working on the developer docs so you can find things quicker.

I agree with the benchmarks bit. We already have infrastructure in place to take care of them: just submit them as a PR to the `eta-benchmarks` repo and any future commits to `eta` will automatically run the new benchmarks. I'll add more instructions on how to go about it.

I agree with your approach. Let's start off with correctness/safety and then optimise where we can without sacrificing on those. At the end of the day, if a dev knows the characteristics of their problem and wants even more perf, they can write up their own Eta library that uses the Java FFI to the ByteBuffer API to customise how memory is allocated, and the job of managing that memory will be up to them.

**Comment by rahulmutt** [comment]
Hi @jonathanknowles, so in trying to implement one of the issues, I ended up doing a large-scale rewrite of the runtime system and as part of these changes, I'm going to also update the MemoryManager, because the rewrite made it clear at exactly what points in the execution we can check for any finalisers to run (which wasn't being done before). 

What I'll do is update this issue once that's merged and you can provide suggestions on how to improve it.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt

Understood! I had already started some of the work (not quite ready for publication), but since your work will update the `MemoryManager`, I'll hold off for the moment to see how things will change.

**Comment by rahulmutt** [comment]
@jonathanknowles The `going-stackless` branch is fairly stable now - you can give it a try and see if that fixes the problem above. The new MemoryManager is quite involved, see below:

https://github.com/typelead/eta/blob/going-stackless/rts/src/eta/runtime/io/MemoryManager.java

I added some comments as well so (hopefully) it should be easy to follow. Let me know if I need to add any more comments.

**Comment by jonathanknowles** [comment]
Hi @rahulmutt 

Sorry for the delay in getting back to you.

I've now had a chance to test the ```going-stackless``` branch. While doing so, I encountered what seems to be a small bug in the ```MemoryManager``` (though I've not yet had a chance to look for the root cause). I've opened a new issue 433 with a simple set of reproduction steps!
