### ISSUE TITLE
'java.lang.NoClassDefFoundError: eta/base/Utils' is happened when java -jar RunMain.jar

### ISSUE THREAD

**Issue by aiya000** [typelead/eta#418]
Hi :dog:

My OS is 'Arch Linux x86_64'

My Java Environment is

```console
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

I'm installing eta.

I did

```console
$ git clone --recursive --branch 0.0.6b7 https://github.com/typelead/eta
$ cd eta
$ ./install.sh
$ cd /tmp
$ nvim Main.hs

module Main where

primes = filterPrime [2..]
    where filterPrime (p:xs) = p : filterPrime [x | x <- xs, x `mod` p /= 0]

main = putStrLn $ "The 101st prime is " ++ show (primes !! 100)

$ eta Main.hs
```

but I got

```console
$ java -jar RunMain.jar
Exception in thread "main" java.lang.NoClassDefFoundError: eta/base/Utils
	at base.ghc.io.encoding.Iconv$zdLrFXOMlvl.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.encoding.Iconv$localeEncodingName.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.Encoding$getFileSystemEncodingzugo.enter(Unknown Source)
	at base.ghc.io.Encoding$getFileSystemEncoding5.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$mkDuplexHandle7.enter(Unknown Source)
	at base.ghc.io.handle.FD$zdLrIFYPlvl4.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.handle.FD$stdout.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:264)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:98)
	at eta.runtime.Rts.hsMain(Rts.java:40)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.base.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
```

I was use eta-0.0.6b7. but it is same.

Can I fix this ?

**Comment by rahulmutt** [comment]
Can you try building master? This should've been fixed by #324.

**Comment by aiya000** [comment]
Thanks!  
I'll try building master :dog:

**Comment by aiya000** [comment]
I tried

```console
$ rm -rf eta
$ git clone --recursive https://github.com/typelead/eta
$ cd eta
$ ./install.sh
$ eta --version
Compiler for the Eta Programming Language, version 0.0.6b8
$ cd /tmp
$ eta Main.hs
$ java -jar RunMain.jar
```

but I got same result... :cry:

```
Exception in thread "main" java.lang.NoClassDefFoundError: eta/base/Utils
	at base.ghc.io.encoding.Iconv$zdLrFXOMlvl.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.encoding.Iconv$localeEncodingName.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.Encoding$getFileSystemEncodingzugo.enter(Unknown Source)
	at base.ghc.io.Encoding$getFileSystemEncoding5.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$mkDuplexHandle7.enter(Unknown Source)
	at base.ghc.io.handle.FD$zdLrIFYPlvl4.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.handle.FD$stdout.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:264)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:98)
	at eta.runtime.Rts.hsMain(Rts.java:40)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.base.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
```

**Comment by rahulmutt** [comment]
Which encoding are you using? Can you share the value of the `LC_ALL` environment variable?

**Comment by aiya000** [comment]
I don't has `$LC_ALL` (`$LC_ALL` is not defined 😢 )

My `$LANG` is `ja_JP.UTF-8` !

**Comment by rahulmutt** [comment]
Ok I wonder if that's the problem. @JulianZhang faced a similar problem and he was using a Chinese encoding. Basically, `javac`'s output is parsed and the markers we use don't work for other encodings. I thought Julian's fix would address all cases, but looks like it won't work for Japanese without some tweeks.

Here is the patch that Julian submitted: https://github.com/typelead/eta/pull/381/files

If you can play around with that code and get it to work for you, I'd be happy to accept a PR! Let me know if you need any help from my side.

**Comment by aiya000** [comment]
Really !? (lol)

OK, I'll try it !  
Please don't get your hopes up X(

**Comment by rahulmutt** [comment]
@aiya000 Does this still happen on the most recent version of Eta (0.7.0b2).

**Comment by aiya000** [comment]
@rahulmutt Sorry, I want to check it...but

I executed

```console
$ git checkout 0.7.0b2
$ LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 ./install.sh
```

and got :sob:

```
Build completed in 3:11m
# eta (for uninstall)
Cleaning files in /home/aiya000/.eta/0.7.0.2
Build completed in 0:01m
# eta (for install)
# eta-pkg (for install)
# etlas (for install)
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
Updating binary package index.
Error when running Shake build system:
* install
user error (Development.Shake.cmd, system command failed
Command: etlas update
Exit code: 1
Stderr:
/home/aiya000/.etlas/binaries/cdnverify.eta-lang.org/index: openFile: does not exist (No such file or directory)

/home/aiya000/.etlas/binaries/cdnverify.eta-lang.org/index: openFile: does not exist (No such file or directory)
```

Do you know the reason?

**Comment by rahulmutt** [comment]
You need to update to the new `etlas-1.2.0.0`. The old etlas will no longer work. See https://groups.google.com/forum/#!topic/eta-discuss/bZEofPXDeJw

**Comment by aiya000** [comment]
It looks like correct :+1:

```shell-session
$ eta Main.hs
$ java -jar RunMain.jar
The 101st prime is 547
```

**Comment by rahulmutt** [comment]
Awesome! I'll close this issue then.

**Comment by aiya000** [comment]
Great 👍
