### ISSUE TITLE
IndexOutOfBoundsException (ArrayList.rangeCheck) when using ByteString.replicate

### ISSUE THREAD

**Issue by jonathanknowles** [typelead/eta#433]
## Environment

Using the [```going-stackless```](https://github.com/typelead/eta/commits/going-stackless) branch.
```
$ eta --version
Compiler for the Eta Programming Language, version 0.0.9b1
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

## Reproduction

Consider the following short program:
```Haskell
module Main where

import System.IO (BufferMode (..), hSetBuffering, stdout)
import qualified Data.ByteString as B

main :: IO ()
main = do
    hSetBuffering stdout NoBuffering
    print $ B.length $ B.replicate (1 * 1024 * 1024    ) 0x20
    print $ B.length $ B.replicate (1 * 1024 * 1024 + 1) 0x20
```

With GHC, running the above produces the following output:
```
1048576
1048577
```

## Expected Behaviour

Running with Eta produces the same output.

## Actual Behaviour

Attempting to create a ```ByteString``` of length 1 MiB succeeds, but attempting to create a ```ByteString``` of length (1 MiB + 1 byte) fails with an ```IndexOutOfBoundsException```:

```
1048576
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1024, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at eta.runtime.io.MemoryManager.getBoundedBuffer(MemoryManager.java:596)
	at eta.base.Utils.c_memset(Utils.java:257)
	at bytestring.data.ByteString$sat_s2QB5.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at bytestring.data.ByteString$$wreplicate.enter(Unknown Source)
	at main.Main$main2.thunkEnter(Unknown Source)
	at eta.runtime.thunk.CAF.enter(CAF.java:28)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$hPutStr3.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Thanks for catching this with exact reproducible steps! 1MB (1048576 bytes) is the smallest block size and this bug appears to be happening at the boundaries.

By the way, the `going-stackless` branch has been merged to master.

**Comment by rahulmutt** [comment]
Hey @jonathanknowles,

Finally got around to taking a look. Thanks a lot for report it! Run your tests again and keep them coming :)

**Comment by jonathanknowles** [comment]
@rahulmutt you're welcome!

I've been a bit busy with other things lately, but as soon as I have time I certainly hope to run a few more experiments :)
