### ISSUE TITLE
Weird output in Text

### ISSUE THREAD

**Issue by AlexeyRaga** [typelead/eta#450]
I am using `text` to encode/decode data, so there are conversions between `Data.Text`, `Data.ByteString` and `Data.ByteString.Lazy`.

I often see that data in `Text` isn't correct. For example, if I send `@moo I love you` then after a series of conversions the data gets corrupted and I get something like `\NUL0love you both` instead of `I love you both`.

I also sometimes (but not always) get this error:

```
Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.ArrayIndexOutOfBoundsException: 7340288
	at java.lang.Thread.getStackTrace(Thread.java:1556)
	at eta.runtime.exception.Exception.raise(Exception.java:182)
	at resourcet.control.monad.trans.Resource$sat_s1FDH.enter(Unknown Source)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at eta.runtime.exception.Exception.catch_(Exception.java:173)
	at resourcet.control.monad.trans.Resource$sat_s1FDI.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:41)
	at resourcet.control.monad.trans.Resource$sat_s1FDV.enter(Unknown Source)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:100)
	at eta.runtime.stg.Capability.schedule(Capability.java:153)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:100)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

P.S. tried implementing the same thing in Haskell and it works fine.

**Comment by rahulmutt** [comment]
On the corrupted data side of the issue, can you see if you can produce a minimal example of the conversions you're doing that's triggering the problem?

**Comment by AlexeyRaga** [comment]
I can try, but it may take me some time.

**Comment by rahulmutt** [comment]
Sure no worries. It'll make it a lot easier to trace if I get some hints on what sequence of conversions causes it to get corrupted.

**Comment by AlexeyRaga** [comment]
Actually reproducing garbage in Text wasn't that hard, here is a quick and dirty one example:

https://github.com/AlexeyRaga/eta-bug-450

It still uses serialisation in the middle (because that is what I was doing), I can try getting rid of it later and do just conversions.

Note that if you run it with `stack` it always passes.

**Comment by AlexeyRaga** [comment]
Oh, there is a simpler case to reproduce this issue: a rundtrip `Data.Text.decodeUtf8 (Data.Text.encodeUtf8 txt))` fails to restore the original message.

I have updated https://github.com/AlexeyRaga/eta-bug-450 to remove serialisation.

**Comment by rahulmutt** [comment]
Great example :) That'll make it *a lot* easier to reproduce.

**Comment by rahulmutt** [comment]
Thanks for reporting this bug! It was indeed a problem with `text` using the MemoryManager API incorrectly - this bug slipped in when we changed the size of Ptr's from 4 bytes to 8 bytes. `etlas update` along with `etlas install text --reinstall` (and re-install all other broken packages) should fix it. Or to make it easy, just do a `./cleaninstall.sh` from master.
