### ISSUE TITLE
NullPointer when trying to use stm-containers library

### ISSUE THREAD

**Issue by rpeszek** [typelead/eta#475]
I am not sure if this ticket belongs here or on eta-hackage,  I decided to put it here.

This package is not on eta-hackage but it compiled just fine. 
Attempt to create a map and add data to it causes
```
Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.NullPointerException
	at stm_containers.stmcontainers.hamt.Nodes$$wa2.enter(Unknown Source)
	at main.Main$createMap2.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stm.STM.atomically(STM.java:67)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```
I have created a trivial example that runs fine with stack and NullPointer-s  with etlas run.

https://github.com/rpeszek/eta-stm-containers

**Comment by rahulmutt** [comment]
@rpeszek To get the fix, clone `master` of the repository, run:

```
> stack install eta-build
> eta-build rts-clean
```

This will install the runtime fix without you having to reinstall eta.

Love the bug reports, keep them coming! :)
