### ISSUE TITLE
NoClassDefFound error for generated class

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#486]
In our project we define a custom monad transformer

```hs
newtype OhuaT m a = OhuaT { runOhuaT' :: RWST CompilerEnv Errors CompilerState m a }
    deriving (Functor, Applicative, Monad, MonadIO, MonadTrans)
```

And an associated class

```hs
class Monad m => MonadOhua m where
    recordError :: Error -> m ()
    modifyState :: (CompilerState -> CompilerState) -> m ()
    getState :: m CompilerState

instance Monad m => MonadOhua (OhuaT m) where
    recordError err = OhuaT $ tell [err]
    modifyState = OhuaT . modify
    getState = OhuaT get
```

Plus a function to initialize the state and run the thing 

```hs
runOhuaT0 :: Monad ctxt => OhuaT ctxt result -> HS.HashSet Binding -> ctxt result
runOhuaT0 f taken = do
    (val, errors) <- evalRWST (runOhuaT' f) (error "Ohua has no environment!") (CompilerState nameGen 0)
    unless (null errors) $ error $ intercalate "\n" errors
    return val
  where
    nameGen = initNameGen taken
```

This all compiles but if i try to run it with even a simple computation

```hs
main = print =<< runOhuaT0 generateBinding mempty
```

I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: ohua_core/ohua/Monad$$fMonadOhuaT
        at main.Main$main1.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
        at eta.runtime.stg.Capability.schedule(Capability.java:150)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ohua_core.ohua.Monad$$fMonadOhuaT
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
```

I want to add that the monad definition is in a different package than the main function.
The main (library only) package with the monad definition is [here](https://github.com/ohua-dev/ohua-core/blob/master/src/Ohua/Monad.hs) and the main function is [here](https://github.com/ohua-dev/ohua-jvm-integration/blob/master/app/DummyMain.hs).

**Comment by rahulmutt** [comment]
Thanks for reporting this! I was able to repro this on my machine without even using sandboxes so that rules out sandboxes as the issue. The classpath in `dist/build/ohua-dummy-main/ohua-dummy-main` does include `ohua-core`, so it's not `etlas`'s fault either.

I'll debug the code generation of `ohua-core` itself and see if I can find out why it's *not* generating `$fMonadOhuaT` when it should be.

**Comment by rahulmutt** [comment]
Found the bug - it's a name clash! Basically, there's two things being generated:
- `$fMonadOhuaT :: (Applicative (OhuaT m), Monad m) => Monad (OhuaT m)` 
   for your monad transformer
- `$fMonadOhuat :: (MonadOhua m, MonadTrans t, Monad (t m)) => MonadOhua (t m)` for your transformer instance for MonadOhua.

**Comment by JustusAdam** [comment]
Yeah sorry ... that overlapping instance is some dark magic I like to use to generate convenient monad transformers 🙈

**Comment by JustusAdam** [comment]
But how's that a clash if one's named `$fMonadOhuaT` and the other `$fMonadOhua`?

**Comment by JustusAdam** [comment]
Ah never mind the thing is not case sensitive right? thats the issue?

**Comment by rahulmutt** [comment]
Yeah it's about case-insensitivity. I literally just replaced the `t`'s with `u`'s in the `MonadOhua` transformer instance and in `ohua-core` and reinstalled and it worked! 

More seriously, I'm going to leave this issue open (or file a new issue) on some compile-time method that detects when there's a name clash. Low priority for now since it happens so rarely, but we need to find a better solution in the long term.

**Comment by rahulmutt** [comment]
To make my last comment more clear:
```haskell
instance {-# OVERLAPPABLE #-} (MonadOhua m, MonadTrans t, Monad (t m)) => MonadOhua (t m) where
```
to
```haskell
instance {-# OVERLAPPABLE #-} (MonadOhua m, MonadTrans u, Monad (u m)) => MonadOhua (u m) where
```
should fix it. Let me know if you encounter anymore issues.

**Comment by JustusAdam** [comment]
Maybe for now we could just try to respect the spaces? So like `Monad_OhuaT` and `MonadOhua_t`? and then escape any undercores in the names themselves for instance by doubling them? So a `instance M a b` would be `M_a_b` and `M_a b` would be `M__a_b`.

And yes I'll try that fix 🙂

**Comment by rahulmutt** [comment]
Great solution! And that encoding maintains readability, so I like it.

**Comment by rahulmutt** [comment]
Would you be interested in implementing this? This is a tiny 5-10 line patch.

I can help you through it by providing hints as to where to do the change.

**Comment by JustusAdam** [comment]
Sure. If you point me to where to do it I think I should be able to do it. 🙂

**Comment by rahulmutt** [comment]
Ok, so we're trying to change the naming of typeclass instance dictionaries and we observe that they start with "$f".

Gripping the codebase for `"$f"` yields two results:
1) `mkForeignExportOcc` - We eliminate this since we're not concerned with foreign exports here.
2) `mkDFunOcc` (full form is "dictionary function") - this is the one we need to change.

Let me know if you need further hints/clarifications.

**Comment by JustusAdam** [comment]
I think I have found the right place to fix this. Its actually the function calling `mkDFunOcc` which is `newDFunName`. 
The compiler also compiles, I just have to test that this change didn't break anything.

**Comment by rahulmutt** [comment]
You can check that you didn't break anything by running `tests/verify/verify.sh`. It will ensure that all classes exist on the classpath and no non-existent classes are referenced.

**Comment by rahulmutt** [comment]
If it works, submit a PR. More advanced stuff will be run by the CI and it'll catch any major breakages if they do happen.

**Comment by JustusAdam** [comment]
So yesterday when thinking about this case-sensitivity issue again I realized that this issue is larger than I thought before.

Haskell itself is case sensitive. Thus the following instances produce two distinct global dicts

```hs
class C ...
instance C TT ...
instance C Tt
```

which are `CTT` and `CTt`. However in Eta both of those will generate a class which is written to the filesystem. On Windows and Mac that means that one of those instance dicts will be overwritten by the other.

This is a case where even introducing `_` for separation does not solve the clash as, in a case insensitive environment `C_TT` and `C_Tt` are still considered the same.

I however believe to have the solution! In GHC there is a function `newGlobalBinder` which is used when a new name is generated. It looks up the name in a map of global names and if the name is already defined it prepends a `0` and tries again with the number increasing. I believe we can solve all of our issues by simply making the lookup into the map case insensitive. 

That means when we first define an instance `CTT` and then `CTt` the lookup for the second one yields a match in `CTT` and we therefore generate a new unique name `CTt0`.

After this change we would not _need_ to insert `_` anymore, however we can leave that in if you think, as I do, that it improves the readability for generated class names.

**Comment by rahulmutt** [comment]
Wonderful analysis! I love this solution. If this is implemented properly, it may obviate the need for case clash checking we were doing in the renamer (implemented by @pparkkin) to give an error to the user if they define two top-level bindings which only differed in case - do you think this could solve that problem as well?

I agree that adding `_` does increase the readability - your `MonadOhua` example really highlights the impact :)

I had to do something similar to avoid case-clashes for the uniques. Before the change I made, you could have two closures with names `sat_sAB` and `sat_sAb` - this happened so frequently in the early days of this project that I had to come up with a permanent solution which involved translating uniques (which are just `Int`'s) to base36 instead of base62 (which can easily produce case clashes).

**Comment by JustusAdam** [comment]
I actually misread the code a bit. I still think this is the way this is done in GHC/Eta but I'll have to carefully go through it once more.
But I do believe that we can fix this intercepting the generation for unique top level bindings.

Whether that solves the top-level bindings for the user depends on whether that mechanism also uses `newGlobalBinder`, but I strongly suspect it does.
