### ISSUE TITLE
Runtime busy waits infinitely in eta.runtime.thunk.UpdateInfoStack.markBackwardsFrom

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#489]
I have a program which does some clojure interop.

The last output I get is `calling isSeq` which comes from here:

```hs
isSeq :: Object -> Bool
isSeq o = trace "calling isSeq" $ asBool $ pureJavaWith (trace "getting seq? var" $ Clojure.coreVar "seq?") $ Clojure.invoke1 o

asBool :: Object -> Bool
asBool o = trace "as bool called" . (fromJava :: JBoolean -> Bool) . unsafeCast $ o

trace str a = unsafeDupablePerformIO $ do
    hPutStrLn stderr str
    return a
```

And the interop functions used are defined as follows:

```hs
data {-# CLASS "clojure.lang.IFn" #-} IFn = IFn (Object# IFn) deriving Class
foreign import java "invoke" invoke1 :: Object -> Java IFn Object
foreign import java "@static clojure.java.api.Clojure.var" mVarNS :: String -> String -> IO (Maybe IFn)

varNS :: String -> String -> IO IFn
varNS name namespace = fromMaybe (error $ "Var not found: " ++ name ++ "/" ++ namespace) <$> mVarNS name namespace

coreVar :: String -> IFn
coreVar v = unsafeDupablePerformIO $ do 
    hPutStrLn stderr $ "Getting core function \'" ++ v ++ "\'"
    !f <- varNS "clojure.core" v
    hPutStrLn stderr "done"
    return f
```

None of the other trace calls produce output and neither does `coreVar`.

The thread dump from visualVM for the main thread looks like this:

```
java.lang.Thread.State: RUNNABLE
        at eta.runtime.thunk.UpdateInfoStack.markBackwardsFrom(UpdateInfoStack.java:104)
        at eta.runtime.thunk.UpdateInfoStack.markBackwardsFrom(UpdateInfoStack.java:89)
        at eta.runtime.stg.Capability.threadPaused(Capability.java:279)
        at eta.runtime.stg.Capability.idleLoop(Capability.java:474)
        at eta.runtime.stg.TSO.suspendInterrupts(TSO.java:221)
        at base.ghc.io.FD$sat_sHBM5.enter(Unknown Source)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at base.foreign.c.Error$$wa1.enter(Unknown Source)
        at base.ghc.io.FD$$wa9.enter(Unknown Source)
        at base.ghc.io.FD$$wa2.enter(Unknown Source)
        at base.ghc.io.FD$$fBufferedIOFD4.enter(Unknown Source)
        at eta.runtime.apply.Function.applyPPV(Function.java:164)
        at base.ghc.io.handle.Internals$$wa3.enter(Unknown Source)
        at base.ghc.io.handle.Text$sat_sHRBA.enter(Unknown Source)
        at eta.runtime.apply.Function.applyPV(Function.java:120)
        at base.ghc.io.handle.Internals$sat_sGE79.enter(Unknown Source)
        at eta.runtime.apply.PAP.apply(PAP.java:31)
        at eta.runtime.apply.PAP.applyV(PAP.java:41)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
        at eta.runtime.exception.Exception.catch_(Exception.java:135)
        at base.ghc.io.handle.Internals$$wa2.enter(Unknown Source)
        at base.ghc.io.handle.Internals$a3_sGDYG.enter(Unknown Source)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:41)
        at base.ghc.io.handle.Internals$withHandlezq1.enter(Unknown Source)
        at base.ghc.io.handle.Internals$wantWritableHandle2.enter(Unknown Source)
        at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Unknown Source)
        at base.ghc.io.handle.Text$$wa6.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr3.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$isSeq2.enter(Unknown Source)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$isSeq1.thunkEnter(Unknown Source)
        at eta.runtime.thunk.CAF.enter(CAF.java:31)
        at eta.runtime.stg.Closure.evaluate(Closure.java:24)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$sat_s14LO.thunkEnter(Unknown Source)
        at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
        at eta.runtime.stg.Closure.evaluate(Closure.java:24)
        at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$isSeq.enter(Unknown Source)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$sat_s15UE.thunkEnter(Unknown Source)
        at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
        at eta.runtime.stg.Closure.evaluate(Closure.java:24)
        at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
        at ohua_jvm_integration.ohua.compat.jvm.Marshal$$w$cfromNative4.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
        at eta.runtime.stg.Capability.schedule(Capability.java:150)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)

   Locked ownable synchronizers:
        - None
```

Weirdly the sampler reports a self time of `0` for all methods (it is started after the program starts to hang).
The program uses ~25% CPU constantly and the heap slowly grows and is then collected again with most objects being `char[]` and `Object[]`.

**Comment by rahulmutt** [comment]
Thanks for the detailed report! Which version of eta are you on?

**Comment by rahulmutt** [comment]
The reason you're not getting output is that you can see `hPutStr` in the stack trace - it's getting stuck while you're printing.

**Comment by rahulmutt** [comment]
I have a feeling this is a manifestation of https://github.com/typelead/eta/commit/fd343d44bae361ec83d13e67f26788f2ed334b27 which is fixed on master. If this is blocking you, I can cut a 0.0.9b2 release soon.

**Comment by rahulmutt** [comment]
Another way to get this fix without doing a full out installation is:

1. Clone the repo.
2. Go to `libraries/rts`.
3. Run `etlas install --allow-boot-library-installs`. It should give you the most recent runtime system with the fix after this. Just go to your project and do `etlas clean` before any further work.

**Comment by JustusAdam** [comment]
So I `stack installed` the, cleaned and reinitialized the sandbox for my project but now `etlas install --dependencies-only` gives me this error

```
Resolving dependencies...
etlas: Could not resolve dependencies:
trying: ohua-jvm-integration-0.7.2 (user goal)
next goal: base (dependency of ohua-jvm-integration-0.7.2)
rejecting: base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0 (only already installed instances can be used)
rejecting: base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (conflict:
ohua-jvm-integration => base>=4.8)
fail (backjumping, conflict set: base, ohua-jvm-integration)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, ohua-jvm-integration
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by rahulmutt** [comment]
Hmm in that case, you may just want to do a straight up clean installation via `./cleaninstall.sh`.

**Comment by JustusAdam** [comment]
I had to delete some directories but now I got it to work. Thanks. 

I think we can close this issue now :)

**Comment by rahulmutt** [comment]
Ok great!
