### ISSUE TITLE
NoSuchMethodError: Comparable.compareTo when using JString's as keys in a Data.Map

### ISSUE THREAD

**Issue by tomshackell** [typelead/eta#498]
```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified Data.Map as Map
import Java

main :: IO ()
main = print $ Map.fromList junk
    where
    junk :: [(JString, Int)]
    junk = [ ("A", 1), ("B", 2) ]
```

Crashes with:

```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Comparable.compareTo(Ljava/lang/Comparable;)I
	at main.Main$$sfromList.enter(Unknown Source)
	at main.Main$main3.thunkEnter(Unknown Source)
	at eta.runtime.thunk.CAF.enter(CAF.java:31)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at containers.data.map.Internal$$fEqMap1.enter(Unknown Source)
	at containers.data.map.Internal$sat_s8H2T.thunkEnter(Unknown Source)
	at eta.runtime.thunk.Thunk.enter(Thunk.java:35)
	at base.ghc.Base$zpzp.enter(Unknown Source)
	at base.ghc.Base$sat_sAR3.thunkEnter(Unknown Source)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$$wa7.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Thanks for reporting this! Fixed on `master`.
