### ISSUE TITLE
Line numbers not showing up 

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#510]
Take the following code:
```
main = readFile "something.txt" >>= putStrLn
```
It gives the following exception:
```
	at base.ghc.Err$error.enter(Err.hs)
	at base.foreign.c.Error$strerror.thunkEnter(Error.hs)
	at eta.runtime.thunk.CAF.enter(CAF.java:31)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.foreign.c.Error$errnoToIOError2.enter(Error.hs)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.IO$unsafeDupablePerformIO.enter(IO.hs)
	at base.foreign.c.Error$errnoToIOError1.thunkEnter(Error.hs)
	at eta.runtime.thunk.CAF.enter(CAF.java:31)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$sat_sGKDF.thunkEnter(Text.hs)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.IO$sat_s8XYT.thunkEnter(IO.hs)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$$wa7.enter(Text.hs)
	at base.ghc.io.handle.Text$hPutStr2.enter(Text.hs)
	at base.ghc.io.handle.Text$hPutStrLn1.enter(Text.hs)
	at base.system.IO$putStrLn1.enter(IO.hs)
	at base.system.IO$putStrLn.enter(IO.hs)
	at eta.runtime.apply.Function.applyPV(Function.java:120)
	at base.ghc.Base$bindIO1.enter(Base.hs)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:100)
	at eta.runtime.stg.Capability.schedule(Capability.java:153)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:100)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

Note that the eta-level code is not generating proper line numbers. @jneira Can you take a look at this?

**Comment by jneira** [comment]
Just this morning i detected that base libraries are being compiled without line numbers. It turns out that etlas has the option `-enable-debug-info` with default value 0, so it calls eta with `-g0` and no line number is generated. 
I can think of some options:
* Change default value of etlas `-enable-debug-info`: but it is used in all program invocations, not only eta
* Don't call eta with `-g0` if `-enable-debug-info` is not explicitly set by the user. i guess it supposes more code changes
* Change eta-build to compile base libraries with debug info in all cases

**Comment by rahulmutt** [comment]
I think it should be the first option - make `-enable-debug-info` with default value 2. We need to have line number information for user written code as well, otherwise the stack traces won't be that helpful.
