### ISSUE TITLE
getContents will throw EtaException: Prelude.undefined

### ISSUE THREAD

**Issue by ChinaXing** [typelead/eta#513]
```
module Main where

import TableParser

main :: IO ()
main = do
  contents <- getContents
  putStrLn $ "HELLO" ++ (show $ length contents)
  return ()
```

then, execute etlas run:

```
lambda-cat.local ➜  table-parser etlas run <<EOF
heredoc> HELLO
heredoc> WORLD
heredoc> max
heredoc> EOF
Preprocessing library for table-parser-0.1.0.0..
Building library for table-parser-0.1.0.0..
Preprocessing executable 'table-parser' for table-parser-0.1.0.0..
Building executable 'table-parser' for table-parser-0.1.0.0..
Running table-parser...
Exception in thread "main" eta.runtime.exception.EtaException: Prelude.undefined
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at eta.runtime.exception.Exception.raise(Exception.java:182)
	at eta.runtime.exception.Raise.thunkEnter(Raise.java:17)
	at eta.runtime.thunk.Thunk.enter(Thunk.java:35)
	at eta.runtime.thunk.Thunk.blackHole(Thunk.java:113)
	at eta.runtime.thunk.CAF.enter(CAF.java:53)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.foreign.c.Error$throwErrnoIfMinus1_3.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.foreign.c.Error$throwErrnoIfMinus1_2.thunkEnter(Unknown Source)
	at eta.runtime.thunk.CAF.enter(CAF.java:31)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$sat_sHRHB.thunkEnter(Unknown Source)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.IO$sat_s8Y2O.thunkEnter(Unknown Source)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.List$$wlenAcc.enter(Unknown Source)
	at main.Main$sat_sK50.thunkEnter(Unknown Source)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at ghc_prim.ghc.CString$unpack_s74B.enter(Unknown Source)
	at ghc_prim.ghc.CString$sat_s74J.thunkEnter(Unknown Source)
	at eta.runtime.thunk.UpdatableThunk.enter(UpdatableThunk.java:18)
	at eta.runtime.stg.Closure.evaluate(Closure.java:24)
	at base.ghc.io.handle.Text$$wa7.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
```

lambda-cat.local ➜  table-parser eta --version
Compiler for the Eta Programming Language, version 0.0.9b1
lambda-cat.local ➜  table-parser etlas --version
etlas version 1.0.1.0
compiled using version 2.1.0.0 of the etlas-cabal library 
lambda-cat.local ➜  table-parser uname  -a
Darwin lambda-cat.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by rahulmutt** [comment]
This is fixed on master. Please do the source installation or pull the latest docker image.
