### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ChinaXing** [typelead/eta#514]
source code: https://github.com/ChinaXing/table-parser

java -jar dist/build/table-parser/table-parser.jar

```
Exception in thread "main" java.lang.StackOverflowError
	at parsec.text.parsec.Char$sat_s1ZZNA.arity(Char.hs)
	at eta.runtime.apply.Function.applyPPPPP(Function.java:270)
	at eta.runtime.thunk.Thunk.applyPPPPP(Thunk.java:186)
	at main.Parser$a20_sZZZZF.enter(Parser.hs:57)
	at eta.runtime.apply.Function.applyPPPPP(Function.java:296)
	at parsec.text.parsec.Prim$$wa.enter(Prim.hs:271)
	at main.Parser$sat_s100U.enter(Parser.hs:57)
	at eta.runtime.apply.Function.applyPPPPP(Function.java:296)
	at eta.runtime.thunk.Thunk.applyPPPPP(Thunk.java:186)
	at main.Parser$sat_s11XD.enter(Parser.hs:66)
	at eta.runtime.apply.Function.applyP(Function.java:102)
	at parsec.text.parsec.Char$sat_s1ZZKF.enter(Char.hs:151)
	at eta.runtime.apply.Function.applyP(Function.java:102)
	at base.data.functor.Identity$$fMonad_Identity_$czgzgze.enter(Identity.hs:46)
	at eta.runtime.apply.Function.applyPP(Function.java:139)
	at parsec.text.parsec.Char$string1.enter(Char.hs:151)
	at main.Parser$$wa20_s11TE.enter(Parser.hs:171)
	at main.Parser$a110_s11TO.enter(Parser.hs)
	at eta.runtime.apply.Function.applyPPPPP(Function.java:296)
	at parsec.text.parsec.Prim$$wa.enter(Prim.hs:271)
	at main.Parser$a111_s11TU.enter(Parser.hs:171)
	at main.Parser$sat_s11XU.enter(Parser.hs)
	at eta.runtime.apply.Function.applyPPP(Function.java:190)
	at parsec.text.parsec.Prim$sat_s1EZZZZ.enter(Prim.hs:256)
	at eta.runtime.apply.Function.applyPPP(Function.java:190)
	at parsec.text.parsec.Char$sat_s1ZZLO.enter(Char.hs:142)
	at eta.runtime.apply.Function.applyP(Function.java:102)
	at base.data.functor.Identity$$fMonad_Identity_$czgzgze.enter(Identity.hs:46)
```

**Comment by rahulmutt** [comment]
CPS-style monads easily blow the stack right now, see #442 for the in-progress solution for this. The workaround for now is to just increase the stack size with `-Xss`.

**Comment by ChinaXing** [comment]
use strict will prevent the stack size needed ？

**Comment by rahulmutt** [comment]
Strictness will not be of any help in this case, as far as I can see. Try swapping out parsec for some other kind of parsing library?
