### ISSUE TITLE
Error printing utf-8 chars

### ISSUE THREAD

**Issue by jneira** [typelead/eta#527]
* When executing this code:
```haskell
main = putStrLn "नमस्ते" >> putStrLn "你好" >>
       putStrLn "привет"
```
* i am getting this error:
```
Exception in thread "main" eta.runtime.exception.EtaException: <stdout>: commitBuffer: failed
        at base.ghc.io.handle.Internals$sat_sG1V2.enter(Internals.hs:172)
        at eta.runtime.apply.Function.applyPV(Function.java:120)
        at eta.runtime.exception.Exception.catch_(Exception.java:174)
        at base.ghc.io.handle.Internals$$wa2.enter(Internals.hs:166)
        at base.ghc.io.handle.Internals$a3_sG1VB.enter(Internals.hs:132)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
        at base.ghc.io.handle.Internals$withHandlezq1.enter(Internals.hs:130)
        at base.ghc.io.handle.Internals$wantWritableHandle2.enter(Internals.hs:236)
        at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Internals.hs:226)
        at base.ghc.io.handle.Text$$wa7.enter(Text.hs:630)
        at base.ghc.io.handle.Text$hPutStr2.enter(Text.hs:553)
        at main.Main$main1.enter(Main.hs:5)
        at main.Main$DZCmain.enter(Main.hs)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:156)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
Caused by: eta.runtime.exception.EtaException: iconvRecoder: failed
        at base.foreign.c.Error$throwErrno1.enter(Error.hs:289)
        at base.ghc.io.encoding.Iconv$$wa.enter(Iconv.hs:186)
        at base.ghc.io.encoding.Iconv$iconvEncoding4.enter(Iconv.hs:136)
        at eta.runtime.apply.PAP.apply(PAP.java:31)
        at eta.runtime.apply.PAP.applyPPV(PAP.java:176)
        at eta.runtime.thunk.Thunk.applyPPV(Thunk.java:166)
        at base.ghc.io.handle.Internals$a2_sG0HS.enter(Internals.hs:379)
        at base.ghc.io.handle.Internals$$wa.enter(Internals.hs:372)
        at base.ghc.io.handle.Internals$$wa3.enter(Internals.hs:510)
        at base.ghc.io.handle.Text$sat_sGL9F.enter(Text.hs:605)
        at eta.runtime.apply.Function.applyPV(Function.java:120)
        at base.ghc.io.handle.Internals$sat_sG244.enter(Internals.hs:255)
        at eta.runtime.apply.PAP.apply(PAP.java:31)
        at eta.runtime.apply.PAP.applyV(PAP.java:41)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
        at eta.runtime.exception.Exception.catch_(Exception.java:136)
        ... 18 more
```

**Comment by jneira** [comment]
Another case: utf-8 chars two bytes long simply are not printed
* with `main = putStrLn "cañá"`
* the output is `ca`

**Comment by jneira** [comment]
* Tested with [the master version of eta](https://github.com/typelead/eta/commit/b24405ae65e48b725d1027d40102b37e9326e45b) in windows 10 with eta/etlas 64 bits and in win 7 with eta/etlas 32 bits

**Comment by jneira** [comment]
* I've rerun the tests with master version 32 bits in windows and i can't reproduce the error but setting the chcp to 1512 or 850. In this cases the similar program in java does not crash but prints the utf-8 chars as ?, but ghc throws an error: `eta-test.exe: <stdout>: commitBuffer: invalid argument (invalid character)`
  * So this would be the expected behaviour in eta

**Comment by jneira** [comment]
* The behaviour is identical in windows 10 with 64 bits eta, so it is not a bug but the actual eta/ghc expected behaviour

**Comment by rahulmutt** [comment]
Thanks for the detailed analysis, @jneira! Is there any bit of documentation needed for Windows users or no?

**Comment by jneira** [comment]
* Maybe we could add some reference to the possible errors in the docs mentioned in https://github.com/typelead/eta/issues/515#issuecomment-331106905
