### ISSUE TITLE
NoSuchMethodError on stg.Closure

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#530]
I get this error message in the stg when I try to run our test cases.

```
Exception in thread "main" java.lang.NoSuchMethodError: eta.runtime.stg.Closure.applyI(Leta/runtime/stg/StgContext;I)Leta/runtime/stg/Closure;, compiling:(ohua/compile_test.clj:11:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at user$eval85.invokeStatic(form-init5552938699833332809.clj:1)
	at user$eval85.invoke(form-init5552938699833332809.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchMethodError: eta.runtime.stg.Closure.applyI(Leta/runtime/stg/StgContext;I)Leta/runtime/stg/Closure;
	at ohua_jvm_integration.ohua.compat.jvm.Compiler$$LrY0Tlvl14.enter(Unknown Source)
	at ohua_jvm_integration.ohua.compat.jvm.Compiler$$fstableZZC0ZZCohuazzmjvmzzmintegrationzzm0zzi7zzi2zzm9gdj4UcZZZZGzzzz6DhxF8uIk20TZZCOhuazziCompatzziJVMzziCompilerZZCnativeCompileWSplice2.enter(Unknown Source)
	at ohua_jvm_integration.ohua.compat.jvm.Compiler$$fstableZZC0ZZCohuazzmjvmzzmintegrationzzm0zzi7zzi2zzm9gdj4UcZZZZGzzzz6DhxF8uIk20TZZCOhuazziCompatzziJVMzziCompilerZZCnativeCompileWSplice1.enter(Unknown Source)
	at ohua_jvm_integration.ohua.compat.jvm.Compiler$$fstableZZC0ZZCohuazzmjvmzzmintegrationzzm0zzi7zzi2zzm9gdj4UcZZZZGzzzz6DhxF8uIk20TZZCOhuazziCompatzziJVMzziCompilerZZCnativeCompileWSplice.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.stg.Closures$EvalIO.enter(Closures.java:111)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalIO(Runtime.java:193)
	at ohua.Compiler.compileAndSpliceEnv(Unknown Source)
	at ohua.lang$ohua.invokeStatic(lang.clj:13)
	at ohua.lang$ohua.invoke(lang.clj:12)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6776)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6837)
	at clojure.lang.Compiler.eval(Compiler.java:6911)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 43 more
Tests failed.
```

I tried to narrow down the issue but kept failing in narrowing the exact place where this error is thrown.

### Additional Information

Etlas version

```
etlas version 1.0.2.0
compiled using version 2.1.0.0 of the etlas-cabal library
```

Eta version

```
Compiler for the Eta Programming Language, version 0.0.9b1
```

### Steps to reproduce

1. Clone the [jvm-integration](https://github.com/ohua-dev/ohua-jvm-integration), [jvm-runtime](https://github.com/ohua-dev/ohua-jvm-runtime) and [jvm-core](https://github.com/ohua-dev/ohua-core) repo.
1. Build the [jvm-runtime](https://github.com/ohua-dev/ohua-jvm-runtime) jar with `lein jar` and place the snapshot jar in the `resources` folder of the `jvm-integration` project.
1. Initialize a sandbox `etlas sandbox init` in the `jvm-runtime` folder.
1. Add the `core` via `add source`
1. Build `etlas build`
1. Generate the `project.clj` file with `stack runhaskell GenProjectClj.hs`
1. Run the test with `lein test :only ohua.compile-test`

I know this is quite a lot but I haven't been able to narrow down where exactly the issue comes in.

To make it easier I have attached the [compiled library as jar](https://github.com/typelead/eta/files/1348905/ohua-jvm-integration.jar.txt) (this is the library jar eta creates, I had to rename it for github to allow me to upload it, just drop the `.txt` and you should be fine). 
This is just the jar for `ohua-jvm-integration` not an uberjar with dependencies. It's in case you want to have a look at the bytecode.
If you like i can also create an uberjar and attach that.

**Comment by rahulmutt** [comment]
This looks just like:
https://github.com/typelead/eta/issues/480

If it's not too much trouble, can you try installing the most recent version on `master` and let me know if that fixes it? 

This is definitely going to be a blocker for you so I can cut a release with the fix asap.

**Comment by JustusAdam** [comment]
I am trying and I replaced `eta` and `eta-pkg` in the `~/.etlas/binaries/...` directory with the version I compiled from master but when I try to build the project it says this:

```
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: ohua-jvm-integration-0.7.2 (user goal)
unknown package: base (dependency of ohua-jvm-integration-0.7.2)
```

Is there some easy way to fix this? Or is there some other way I should use to get make it build with the version from `master`?

**Comment by JustusAdam** [comment]
Also I apologize for failing to see that this was a duplicate, I searched the issues but I didn't realize that I was only searching the open ones.

**Comment by JustusAdam** [comment]
After rereading the other issue I should mention that I used the binary install.

**Comment by rahulmutt** [comment]
When you built from `master`, did you run `./install.sh`? Replacing the binaries like that should work as long as your package databases are properly configured. One way to verify this is to share the contents of the following directories:

`~/.eta/*`
`~/.etlas/lib/*`

**Comment by JustusAdam** [comment]
I only ran `stack build` and symlinked the binaries. But I can try the script as well.

**Comment by rahulmutt** [comment]
You actually need to run the script since it sets up the initial package database for you with the compiler-recognized libraries (like `base`). I should probably make this more clear in the docs somewhere.

**Comment by rahulmutt** [comment]
Once you run `./install.sh` it'll actually add `eta` to your PATH. I encourage you to do the following instead of replacing your binaries:

1) Make a backup of `~/.etlas/binaries/eta`.
2) Set the contents of `~/etlas/binaries/eta`.
```
$PATH
$PATH
```
3) When you want to use the old binaries, simply restore the backup you created in (1).

**Comment by rahulmutt** [comment]
The process above should be ideally be doable via an `etlas` command - that's on the to-do list. I hoped to get it in before the next release.

**Comment by JustusAdam** [comment]
Ah yes. Very nice. That did fix it. Very nice. Well for now since I can compile the project again you don't **have** to make a release.
