### ISSUE TITLE
Typechecker should ensure Maybe [Primitive Type] is not a valid argument type in FFI

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#539]
I have a simple test case to verify my FFI conversions work as intended.

```hs 
test :: IO ()
test = do
    let sym = Local "b" :: ResolvedSymbol
    unless (sym == fromNative (toNative sym)) $ putStrLn "failed"
```

Which fails with the following verify error:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ohua_jvm_integration/ohua/compat/jvm/Marshal$$w$ctoNative8.enter(Leta/runtime/stg/StgContext;)Leta/runtime/stg/Closure; @464: invokespecial
  Reason:
    Type null (current frame, stack[5]) is not assignable to integer
  Current Frame:
    bci: @464
    flags: { }
    locals: { 'ohua_jvm_integration/ohua/compat/jvm/Marshal$$w$ctoNative8', 'eta/runtime/stg/StgContext', 'eta/runtime/stg/Closure', 'eta/runtime/stg/Closure', 'eta/runtime/stg/Closure', 'eta/runtime/stg/Closure','eta/runtime/stg/Closure', 'eta/runtime/stg/Closure', 'eta/runtime/stg/Closure', 'eta/runtime/stg/Closure', 'eta/runtime/io/ByteArray', integer, integer, 'java/lang/String', 'eta/runtime/stg/Closure' }
    stack: { 'eta/runtime/stg/TSO', integer, uninitialized 457, uninitialized 457, 'java/lang/String', null }
  Bytecode:
    0x0000000: 2b05 b600 3d4d 2c2b b600 434e 2dc0 0046
    0x0000010: b600 48ab 0000 0019 0000 0002 0000 0001
    0x0000020: 0000 0044 0000 0002 0000 00de 2dc0 0009
    0x0000030: 59b4 004c 3604 572b b400 5059 03b6 0056
    0x0000040: bb00 0e59 1504 b700 5a3a 05b6 005d 2b04
    0x0000050: 1905 b600 6101 b02d c000 1159 b400 673a
    0x0000060: 0457 1904 2bb6 0043 3a05 1905 c000 1659
    0x0000070: b400 6a3a 0659 b400 6f36 0759 b400 7236
    0x0000080: 0857 1507 1508 6036 09bb 0019 5919 0615
    0x0000090: 09b7 0075 3a0a 2b04 1507 b600 7819 0a2b
    0x00000a0: b600 7b3a 0b2b 0519 0bb6 007d b800 802b
    0x00000b0: b600 7b57 2b04 b600 86c0 0089 3a0c 2bb4
    0x00000c0: 0050 5903 b600 5619 0cb8 008b 3a0d b600
    0x00000d0: 5d2b b400 5059 03b6 0056 bb00 1c59 190d
    0x00000e0: b700 913a 0eb6 005d 2b04 190e b600 6101
    0x00000f0: b02d c000 1f59 b400 943a 0459 b400 953a
    0x0000100: 0557 1904 2bb6 0043 3a06 1906 c000 2459
    0x0000110: b400 973a 0759 b400 983a 0857 1908 2bb6
    0x0000120: 0043 3a09 1909 c000 1659 b400 6a3a 0a59
    0x0000130: b400 6f36 0b59 b400 7236 0c57 2b05 1907
    0x0000140: b600 7d2b 0419 0ab6 0061 2b04 150b b600
    0x0000150: 782b 0515 0cb6 0078 b800 992b b600 7b57
    0x0000160: 2b04 b600 86c0 0089 3a0d 1905 2bb6 0043
    0x0000170: 3a0e 190e c000 46b6 0048 049f 0045 190e
    0x0000180: c000 2c59 b400 9f3a 0f57 190f 2bb6 0043
    0x0000190: 3a10 1910 c000 3159 b400 a036 1157 2bb4
    0x00001a0: 0050 5903 b600 56bb 0027 5919 0d15 11b7
    0x00001b0: 009c 3a12 b600 5d2b 0419 12b6 0061 01b0
    0x00001c0: 2bb4 0050 5903 b600 56bb 0027 5919 0d01
    0x00001d0: b700 9c3a 0fb6 005d 2b04 190f b600 6101
    0x00001e0: b0
  Stackmap Table:
    append_frame(@6,Object[#65])
    append_frame(@44,Object[#65])
    same_frame(@87)
    same_frame_extended(@241)
    full_frame(@448,{Object[#4],Object[#59],Object[#65],Object[#65],Object[#65],Object[#65],Object[#65],Object[#65],Object[#65],Object[#65],Object[#109],Integer,Integer,Object[#137],Object[#65]},{})

        at ohua_jvm_integration.ohua.compat.jvm.Marshal.$w$ctoNative8(Marshal.hs)
        at main.ConversionTests$testAll1.enter(ConversionTests.hs:91)
        at main.Main$DZCmain.enter(Spec.hs:4)
        at eta.runtime.apply.Function.applyV(Function.java:16)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:156)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:101)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
```

The FFI code responsible for the conversion is this:

```hs
class Class (NativeType a) => NativeConverter a where
    type NativeType a
    fromNative :: NativeType a -> a
    toNative :: a -> NativeType a

data {-# CLASS "ohua.alang.ResolvedSymbol" #-} NResolvedSymbol = NResolvedSymbol (Object# NResolvedSymbol) deriving Class

instance NativeConverter ResolvedSymbol where
    type NativeType ResolvedSymbol = NResolvedSymbol

    fromNative nsym =
        case (safeDowncast nsym, safeDowncast nsym, safeDowncast nsym) of
            (Just v, _, _) -> Local $ fromNative $ nLocalBindingBinding v
            (_, Just v, _) -> Sf (fromNative $ nSfBindingFnName v) (fmap fromNative $ nSfBindingId v)
            (_, _, Just v) -> Env $ fromNative $ nEnvBindingId v
            _ -> error "unconvertable"
    toNative (Local l) = superCast $ newLocalBinding $ toNative l
    toNative (Sf name num) = superCast $ newSFBinding (toNative name) (fmap unFnId num)
    toNative (Env n) = superCast $ newEnvBinding $ unwrapHostExpr n

data {-# CLASS "ohua.alang.ResolvedSymbol$Local" #-} NLocalBinding = NLocalBinding (Object# NLocalBinding) deriving Class

type instance Inherits NLocalBinding = '[NResolvedSymbol]

foreign import java "@field binding" nLocalBindingBinding :: NLocalBinding -> NBinding
foreign import java "@new" newLocalBinding :: NBinding -> NLocalBinding


data {-# CLASS "ohua.alang.ResolvedSymbol$Sf" #-} NSfBinding = NSfBinding (Object# NSfBinding) deriving Class

type instance Inherits NSfBinding = '[NResolvedSymbol]

foreign import java "@field fnName" nSfBindingFnName :: NSfBinding -> JString
foreign import java "@field fnId" nSfBindingId :: NSfBinding -> Maybe JInteger
foreign import java "@new" newSFBinding :: JString -> Maybe Int -> NSfBinding


data {-# CLASS "ohua.alang.ResolvedSymbol$Env" #-} NEnvBinding = NEnvBinding (Object# NEnvBinding) deriving Class

type instance Inherits NEnvBinding = '[NResolvedSymbol]

foreign import java "@field id" nEnvBindingId :: NEnvBinding -> JInteger
foreign import java "@new" newEnvBinding :: Int -> NEnvBinding
```

If you need more of the code you find the Haskell types [here](https://github.com/ohua-dev/ohua-core/blob/master/src/Ohua/ALang/Lang.hs) and the java classes [here](https://github.com/ohua-dev/ohua-jvm-integration/blob/master/src/java/ohua/alang/ResolvedSymbol.java)

**Comment by rahulmutt** [comment]
```
foreign import java "@new" newSFBinding :: JString -> Maybe Int -> NSfBinding
```
Are you sure you meant `Maybe Int`? That means you're trying to make `int`-nullable which doesn't make sense! 

Maybe you meant `Maybe JInteger`? `JInteger` is defined in `Java.Wrappers` and should most likely be available when you import `Java`.

**Comment by rahulmutt** [comment]
I'll leave this open so that I remember to add a check in the typechecker to throw an error for things like `Maybe Int`.

**Comment by rahulmutt** [comment]
Closing, as this has been resolved.

**Comment by JustusAdam** [comment]
Out of curiosity, wouldn't it make more sense to marshal `Int#` to `int` and `Int` to `Integer`?

**Comment by rahulmutt** [comment]
A normal user should never have to deal with `Int#` when he codes, that's the main reason for it. But even though you specify `Int`, internally it compiles down to `Int#` so you get all of GHC's unboxing optimizations playing nicely with FFI.
