### ISSUE TITLE
NPE when reading with Data.Text.IO

### ISSUE THREAD

**Issue by swingbit** [typelead/eta#541]
This simple example uses `Data.Text.IO` to implement a basic `cat`: reads from a file, outputs from stdout:
```
$ cat Main.hs 
module Main where

import System.Environment (getArgs)
import qualified Data.Text.IO as TIO

main :: IO ()
main
  = do argv <- getArgs
       text <- TIO.readFile $ head argv
       TIO.putStr text
```

Here is its cabal file:
```
$ cat tmp.cabal
name:                tmp
version:             0.1.0.0
license:             BSD3
license-file:        LICENSE
author:              Me
maintainer:          a@ab.c
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10

executable tmp
  main-is:             Main.hs
  build-depends:       base >=4.8 && <4.9, text
  default-language:    Haskell2010
```

When I run it (using the cabal file as input):
```
etlas run -- tmp.cabal 
Preprocessing executable 'tmp' for tmp-0.1.0.0..
Building executable 'tmp' for tmp-0.1.0.0..
[1 of 1] Compiling Main             ( Main.hs, dist/build/tmp/tmp-tmp/Main.jar )
Linking dist/build/tmp/tmp.jar ...
Running tmp...
Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.NullPointerException
	at base.ghc.io.handle.Internals$sat_sFYZZA.apply1V(Internals.hs:179)
	at eta.runtime.exception.Exception.catch_(Exception.java:167)
	at base.ghc.io.handle.Internals$$wa2.enter(Internals.hs:166)
	at base.ghc.io.handle.Internals$a3_sFZZ1A.applyV(Internals.hs:125)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.ghc.io.handle.Internals$wantReadableHandle1.apply3V(Internals.hs:130)
	at text.data.text.IO$getContents2.apply1V(IO.hs)
	at main.Main$main1.applyV(Main.hs)
	at main.Main$DZCmain.applyV(Main.hs)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
	at eta.runtime.stg.Capability.schedule(Capability.java:157)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
Caused by: eta.runtime.exception.EtaException: JException java.lang.NullPointerException
	at text.data.text.IO$lvl10_s8VI7.apply1V(IO.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:167)
	at text.data.text.IO$a1_s8VJG.apply1V(IO.hs)
	at text.data.text.IO$sat_s8VL1.apply1V(IO.hs)
	at base.ghc.io.handle.Internals$wantReadableHandle2.apply2V(Internals.hs:295)
	at base.ghc.io.handle.Internals$sat_sFZZ1C.apply1V(Internals.hs:261)
	at eta.runtime.apply.PAP1_1.applyV(PAP1_1.java:16)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:125)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	... 13 more
Caused by: java.lang.NullPointerException
	at text.data.text.internal.IO$$wa.enter(IO.hs)
	at text.data.text.IO$sat_s8VJR.applyV(IO.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	... 20 more
```

Notice that using `System.IO` instead of `Data.Text.IO` works fine.
I have also tried `Data.Text.Lazy.IO`, it still fails.

Some details:
```
$ etlas --version
etlas version 1.0.2.0
compiled using version 2.1.0.0 of the etlas-cabal library 
```
```
Compiler for the Eta Programming Language, version 0.0.9b2
```
```
$ java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
```

**Comment by rahulmutt** [comment]
Thanks for reporting this! I was able to reproduce this locally on the most recent build.

**Comment by rahulmutt** [comment]
Fixed on `master`.
