### ISSUE TITLE
Runtime error using FFI wrapper...

### ISSUE THREAD

**Issue by bkyrlach** [typelead/eta#544]
I'm trying to implement [Rapidoid ReqRespHandler](https://github.com/rapidoid/rapidoid/blob/master/rapidoid-http-fast/src/main/java/org/rapidoid/http/ReqRespHandler.java) and even though the bytecode that's generated looks correct, I get an ```java.lang.AbstractMethodError``` at runtime.

The interface method I'm trying to wrap is this...

```Java
Object execute(Req req, Resp resp) throws Exception;
```

I have the following FFI declaration...

```Haskell
  foreign import java unsafe "@wrapper execute"
    handler :: (Request -> Response -> Java Handler Object) -> Handler
```

This compiles just fine, but at runtime, I get this error whenever I hit an endpoint.

```
16:43:00.402 [executor2] ERROR o.r.h.impl.lowlevel.LowLevelHttpIO - Error occurred when handling request! | error = java.lang.AbstractMethodError: eta.org.rapidoid.http.ReqRespHandler$Eta.execute(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
java.lang.AbstractMethodError: eta.org.rapidoid.http.ReqRespHandler$Eta.execute(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at org.rapidoid.http.handler.optimized.DelegatingParamsAwareReqRespHandler.handleReq(DelegatingParamsAwareReqRespHandler.java:48)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqAndPostProcess(AbstractDecoratingHttpHandler.java:336)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqMaybeInTx(AbstractDecoratingHttpHandler.java:265)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.access$700(AbstractDecoratingHttpHandler.java:48)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3.run(AbstractDecoratingHttpHandler.java:223)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 ```

If I decompile the jar that's generated, I see that the class that the compiler generated to implement this interface looks correct. Why am I getting this runtime error?

**Comment by rahulmutt** [comment]
The FFI declaration looks fine to me. It would be great it you can create a github repo with a minimal setup so I can play around with this. Thanks!

**Comment by bkyrlach** [comment]
Sure thing... repo is [here](https://github.com/bkyrlach/EtaExample) 

If you do ```etlas run``` and then hit [http://localhost:8080/test](http://localhost:8080/test) you should see the error.

**Comment by rahulmutt** [comment]
Ok I've done a successful repro. I'll see if I can tweak the example to make it work. 

At the outset, something looks strange:

It's giving an error about a method signature `(Object, Object)Object` and the method signature you actually generated was `(Req, Resp)Object` for execute.

**Comment by bkyrlach** [comment]
Yeah, I verified that it's generating the correct implementation by decompiling the output jar. Hope you figure it out. :)

**Comment by rahulmutt** [comment]
Ok, I think I see the problem:
```java
public interface ReqRespHandler extends TwoParamLambda<Object, Req, Resp> {

	Object execute(Req req, Resp resp) throws Exception;

}
```
Note that it derives from `TwoParamLambda` and `execute` is an attempt to *override* it. Generics compile down all parameters to just `Object` so it actually expects an implementation for `Object execute(Object req, Object resp)`.

So the correct way to do this is:
```haskell
foreign import java unsafe "@wrapper execute"
  handler :: (Object -> Object -> Java Handler Object) -> Handler

mkHandler :: (Request -> Response -> Java Handler Object) -> Handler
mkHandler f = handler (\req resp -> f (unsafeCast req) (unsafeCast resp))
```

And then use `mkHandler` for all your implementations. I tried this with your sample project and it worked.

**Comment by bkyrlach** [comment]
Thank you so much for your help. Did you have to change anything else? I made the change you suggested, but I just get a different error.

```
11:38:39.960 [executor2] ERROR o.r.h.impl.lowlevel.LowLevelHttpIO - Error occurred when handling request! | error = java.lang.IncompatibleClassChangeError: Found interface org.rapidoid.http.Resp, but class was expected
java.lang.IncompatibleClassChangeError: Found interface org.rapidoid.http.Resp, but class was expected
	at main.Main$sat_sAKD.applyO(Main.hs)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:150)
	at main.Main$eta_sAKG.thunkEnter(Main.hs)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:18)
	at base.java.TopHandler$runJava1.enter(TopHandler.hs:25)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP1_1.applyO(PAP1_1.java:51)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:157)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at eta.org.rapidoid.http.ReqRespHandler$Eta.execute(Unknown Source)
	at org.rapidoid.http.handler.optimized.DelegatingParamsAwareReqRespHandler.handleReq(DelegatingParamsAwareReqRespHandler.java:48)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqAndPostProcess(AbstractDecoratingHttpHandler.java:336)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqMaybeInTx(AbstractDecoratingHttpHandler.java:265)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.access$700(AbstractDecoratingHttpHandler.java:48)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3.run(AbstractDecoratingHttpHandler.java:223)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bkyrlach** [comment]
I was able to get something to work, but it certainly feels wrong. Here are the changes I had to make.

I added definition for the implementation of ```Resp```.

```Haskell
  data {-# CLASS "org.rapidoid.http.impl.RespImpl" #-} ResponseImpl = ResponseImpl (Object# ResponseImpl)
    deriving Class

  type instance Inherits ResponseImpl = '[Response]
```

I also had to change the definition of result...

```Haskell
  foreign import java unsafe result :: Object -> Java ResponseImpl Response

  mkResult :: String -> Java ResponseImpl Response
  mkResult s = result $ superCast ((toJava s) :: JString)
```

This works, but having to tie things to a concrete implementation of the ```Resp``` interface seems very wrong. Any thoughts?

**Comment by rahulmutt** [comment]
`Response` is an interface so you must use the `@interface` annotation in your import string.

```haskell
foreign import java unsafe "@interface" result :: (a <: Object) => a -> Java Response Response
```
I did the `a <: Object` so that it automatically inserts `superCast` for you. 

For your particular example:
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Rapidoid
import Java
import System.IO.Unsafe

main :: IO ()
main = do
  putStrLn "Hello from Eta!"
  route <- java $ http_get "/test"
  javaWith route $ serve $ mkHandler (\req resp -> return $ superCast $ unsafePerformIO $ javaWith resp $ result ("Hello from ETA" :: JString))
  putStrLn "Inside Java!"
  putStrLn "Goodbye!"
```

This works successfully. The last time, I forgot to run the request.

**Comment by bkyrlach** [comment]
That works. Thank you so much!

**Comment by rahulmutt** [comment]
No problem! Feel free to file issues on any questions you have as well.
