### ISSUE TITLE
"Duplicate field name&signature" error in class generated from a module with foreign exports

### ISSUE THREAD

**Issue by jneira** [typelead/eta#547]
When  trying to execute code which depends on a class with foreign export i got this error:
```
Exception in thread "main" java.lang.ClassFormatError: Duplicate field name&signature in class file wai_servlet/network/wai/servlet/Examples
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at main.Main$main1.applyV(Main.hs:4)
        at main.Main$DZCmain.applyV(Main.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:157)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
```
Examining the class generated we can see that the duplicated method is:
```java
public static Closure servShowReq()
  {
    if (servShowReq == null) {
      servShowReq = new servShowReq();
    }
    return servShowReq;
  }
``` 
that corresponds with the code in [Network.Wai.Servlet.Examples](https://github.com/jneira/wai-servlet/blob/master/src/Network/Wai/Servlet/Examples.hs#L72-L75) :
```haskell
servShowReq :: DefaultWaiServletApplication
servShowReq = makeServiceMethod appShowReq 

foreign export java "service" servShowReq :: DefaultWaiServletApplication
```

**Comment by rahulmutt** [comment]
I fixed this on master. If this is seriously biting anyone who is not doing source installation, please let me know and I can do a prompt binary release. Otherwise, I'll wait till we have a couple more changes before the next one.

**Comment by jneira** [comment]
i've tested it again with a084b2db version and the error seems to be fixed
