### ISSUE TITLE
ClassFormatError: Invalid method Code length

### ISSUE THREAD

**Issue by carymrobbins** [typelead/eta#557]
When attempting to run Eta's Lexer via Eta, I get the following exception -

```
Exception in thread "main" java.lang.ClassFormatError: Invalid method Code length 185470 in class file eta_parser/language/eta/parser/Lexer$$Lr1SA4Elvl4456
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at main.Main$main1.applyV(Test.hs:24)
        at main.Main$DZCmain.applyV(Test.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:157)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
Test suite test: FAIL
```

**Comment by rahulmutt** [comment]
This is due to the fact that `alex` generates a huge lexer state transition table and the code to initialize it takes that much space since there are so many different states.

The state transition function is also pretty huge, but the size should decrease with a patch I'm working on now to make static method dispatch the default when the function is known at compile-time.

**Comment by rahulmutt** [comment]
We found a work around for this special case, and a general solution is tracked in https://github.com/typelead/eta/issues/558.
