### ISSUE TITLE
Method "fromEnum (x :: Int64)" throws "value x is outside of Int's bounds"

### ISSUE THREAD

**Issue by jneira** [typelead/eta#570]
* Detected when trying to use the function `epochTimeToHTTPDate :: EpochTime -> HTTPDate` from http-date package
* Minimal example:
```haskell
main = do
  let i64 :: Int64
      i64 = 1511875782295
  print i64
  print $ fromEnum i64
```
* Output:
```shell
1511875782295
Exception in thread "main" eta.runtime.exception.EtaException: Enum.fromEnum{Int
64}: value (1511875782295) is outside of Int's bounds (-2147483648,2147483647)
        at base.ghc.Err$error.apply1(Err.hs:35)
        at base.ghc.Enum$$Lr15YTlvl25.apply3(Enum.hs)
        at base.ghc.Enum$fromEnumError.apply3(Enum.hs:131)
        at base.ghc.Int$$Lr9W8Ulvl13.apply1(Int.hs)
        at base.ghc.Int$$fEnum_Int6.applyL(Int.hs)
        at base.ghc.Int$$w$cfromEnum.applyL(Int.hs:576)
        at main.Main$main4.thunkEnter(Main.hs)
        at eta.runtime.thunk.CAF.evaluate(CAF.java:29)
        at base.ghc.io.handle.Text$$wa7.enter(Text.hs:586)
        at base.ghc.io.handle.Text$hPutStr2.apply3V(Text.hs:553)
        at main.Main$main1.applyV(Main.hs:11)
        at main.Main$DZCmain.applyV(Main.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:157)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
```

**Comment by jneira** [comment]
* The cause could be the implementation of `epochTimeToHTTPDate :: EpochTime -> HTTPDate`:
```haskell
epochTimeToHTTPDate :: EpochTime -> HTTPDate
epochTimeToHTTPDate x = defaultHTTPDate {
    hdYear   = y
  , hdMonth  = m
  , hdDay    = d
  , hdHour   = h
  , hdMinute = n
  , hdSecond = s
  , hdWkday  = w
  }
  where
    w64 :: Word64
    w64 = fromIntegral $ fromEnum x
    (days',secs') = w64 `quotRem` 86400
    days = fromIntegral days'
    secs = fromIntegral secs'
    -- 1970/1/1 is Thu (4)
    w = (days + 3) `rem` 7 + 1
    (y,m,d) = toYYMMDD days
    (h,n,s) = toHHMMSS secs
```
* It is using fromEnum and it must return an Int. EpochTime is an alias for CTime (wirh constructor CTime Int64)
* But it is a little bit strange that the function would be wrong :-/

**Comment by jneira** [comment]
* Never mind, it turns out EpochTime is in seconds and i was trying to use milliseconds instead

**Comment by rahulmutt** [comment]
Anyways, thanks for reporting @jneira! It's better reporting something you feel is wrong than letting it go.
