### ISSUE TITLE
IllegalMonitorStateException thrown from Eta

### ISSUE THREAD

**Issue by carymrobbins** [typelead/eta#579]
Occurs when trying to run JUnit tests manually; may be related to an `IncompatibleClassChangeError` I was attempting to work around.

```
Exception in thread "main" java.lang.IllegalMonitorStateException
        at main.Tests.testClasses(Tests.hs)
        at main.Main.main1(Main.hs:7)
        at main.Main.DZCmain(Main.hs)
        at main.Main$DZCmain.applyV(Main.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:157)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
This is actually a bug. The lazy initialization code for thunks uses a synchronized block to prevent access from multiple threads but it doesn't have a exception handler like it should. This is causing a problem for JIT as well which is not able to compile such methods.
