### ISSUE TITLE
Support accessing protected fields/methods via the FFI

### ISSUE THREAD

**Issue by carymrobbins** [typelead/eta#600]
It is currently impossible to access protected fields/methods from the FFI. The workaround is to write a wrapper class which "promotes" the protected fields/methods to public ones.

Below is an example stack trace and test case demonstrating the issue.

```
tried to access field com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.myFixture from class main.tests.EtaSyntaxHighlighterTest
java.lang.IllegalAccessError: tried to access field com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.myFixture from class main.tests.EtaSyntaxHighlighterTest
	at main.tests.EtaSyntaxHighlighterTest.$wa(EtaSyntaxHighlighterTest.hs:51)
	at main.tests.EtaSyntaxHighlighterTest.$fe_testSimple1(EtaSyntaxHighlighterTest.hs)
	at main.tests.EtaSyntaxHighlighterTest.$fe_testSimple(EtaSyntaxHighlighterTest.hs)
	at main.tests.EtaSyntaxHighlighterTest$$fe_testSimple.applyO(EtaSyntaxHighlighterTest.hs)
	at eta.runtime.thunk.Thunk.applyO(Thunk.java:143)
	at base.java.TopHandler.runJava1(TopHandler.hs:25)
	at base.java.TopHandler.runJava(TopHandler.hs)
	at base.java.TopHandler$runJava.enter(TopHandler.hs)
	at eta.runtime.apply.PAP1_1.applyO(PAP1_1.java:51)
	at eta.runtime.stg.Closures$EvalJava.enter(Closures.java:149)
	at eta.runtime.stg.Capability.schedule(Capability.java:157)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
	at eta.runtime.Runtime.evalJava(Runtime.java:201)
	at com.typelead.EtaSyntaxHighlighterTest.testSimple(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$11(UsefulTestCase.java:339)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$12(UsefulTestCase.java:371)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:40)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:370)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:358)
	at com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.doRunTests(LightPlatformCodeInsightFixtureTestCase.java:99)
	at com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.runTest(LightPlatformCodeInsightFixtureTestCase.java:90)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:384)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$2.run(EdtTestUtil.kt:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```haskell
module Tests.EtaSyntaxHighlighterTest where

import P

import FFI.Com.IntelliJ.Psi.PsiFile

import IntelliJ.TestFramework.UsefulTestCase

--------------
-- FileType --
--------------

data {-# CLASS "com.intellij.openapi.fileTypes.FileType" #-}
  FileType = FileType (Object# FileType)
  deriving Class

foreign import java unsafe
  "@static @field com.typelead.intellij.plugin.eta.lang.EtaFileType.INSTANCE"
  etaFileType :: FileType

----------------------------
-- CodeInsightTestFixture --
----------------------------

data {-# CLASS "com.intellij.testFramework.fixtures.CodeInsightTestFixture" #-}
  CodeInsightTestFixture = CodeInsightTestFixture (Object# CodeInsightTestFixture)
  deriving Class

foreign import java unsafe configureByText
  :: FileType -> JString -> Java CodeInsightTestFixture PsiFile

foreign import java unsafe testHighlighting
  :: Java CodeInsightTestFixture Long

---------------------------------------------
-- LightPlatformCodeInsightFixtureTestCase --
---------------------------------------------

data {-# CLASS "com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase" #-}
  LightPlatformCodeInsightFixtureTestCase = LightPlatformCodeInsightFixtureTestCase (Object# LightPlatformCodeInsightFixtureTestCase)
  deriving Class

type instance Inherits LightPlatformCodeInsightFixtureTestCase = '[UsefulTestCase]

foreign import java unsafe "@field myFixture" getMyFixture
  :: Java LightPlatformCodeInsightFixtureTestCase CodeInsightTestFixture

------------------------------
-- EtaSyntaxHighlighterTest --
------------------------------

data {-# CLASS "com.typelead.EtaSyntaxHighlighterTest" #-}
  EtaSyntaxHighlighterTest = EtaSyntaxHighlighterTest (Object# EtaSyntaxHighlighterTest)
  deriving Class

type instance Inherits EtaSyntaxHighlighterTest = '[LightPlatformCodeInsightFixtureTestCase]

foreign export java testSimple
           :: Java EtaSyntaxHighlighterTest ()
testSimple :: Java EtaSyntaxHighlighterTest ()
testSimple = do
  this <- getThis
  myFixture <- superCast this <.> getMyFixture
  myFixture <.> configureLines
    [ "module Main where"
    , "main = putStrLn \"Hello world" -- Unterminated string
    ]
  myFixture <.> testHighlighting
  return ()
  where
  configureLines xs = configureByText etaFileType (foldMap (<> "\n") xs)
```

**Comment by rahulmutt** [comment]
Support for protected fields is missing, but support for protected methods is already there:
```java
public class SuperClass {
    protected void protectedMethod() {
        System.out.println("Hello!");
    }
}
```

```haskell
import Java

data SuperClass = SuperClass @SuperClass
  deriving Class

-- Exporting ChildClass
data ChildClass = ChildClass @ChildClass
  deriving Class

type instance Inherits ChildClass = '[SuperClass]

foreign export java "@super protectedMethod" protectedMethod
  :: Java ChildClass ()

foreign export java callsProtectedMethod :: Java ChildClass ()
callsProtectedMethod = protectedMethod
-- Done exporting

-- Importing ChildClass
foreign import java "@new" newChildClass :: IO ChildClass
foreign import java "callsProtectedMethod" _callsProtectedMethod :: Java ChildClass ()
-- Done importing

main :: IO ()
main = do
  childClass <- newChildClass
  java $ childClass <.> _callsProtectedMethod
```

I'll add support for these as well:
- protected fields
- protected static fields
- protected static methods
