### ISSUE TITLE
StackOverflowError when calling eta.runtime.io.MemoryManager.allocateBuffer with a big size

### ISSUE THREAD

**Issue by jneira** [typelead/eta#639]
* When calling `eta.runtime.ioMemoryManager.allocateBuffer` with a size around 4200000 it throws this exception:
```
java.lang.StackOverflowError
	at java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.add(Unknown Source)
	at eta.runtime.storage.ManagedHeap.setActiveNursery(ManagedHeap.java:72)
	at eta.runtime.storage.Nursery.allocateBlocksFromNext(Nursery.java:63)
	at eta.runtime.storage.Nursery.allocateBlocks(Nursery.java:43)
	at eta.runtime.storage.Nursery.allocateBlocksFromNext(Nursery.java:64)
	at eta.runtime.storage.Nursery.allocateBlocks(Nursery.java:43)
....
```
* Usually eta doesn't allocate such large buffers (bytestrings are allocated using smaller chunks), but maybe it is possible to trigger the error

**Comment by jneira** [comment]
* The maximum size that you can allocate is 2^22 (4194304) bytes, with 4194305 it throws the error

**Comment by rahulmutt** [comment]
This is resolved with the recent memory manager changes. Moreover, the test you ignored to catch this has now be un-ignored and it's passing.
