### ISSUE TITLE
[eta-benchmarks] Selector Thunk bug in spectral/multiplier

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#651]
https://github.com/typelead/eta-benchmarks/issues/5

**Comment by rahulmutt** [comment]
Related bug in `spectral/simple`:
```
	Suppressed: java.lang.NoSuchFieldError: x1
		at main.Main.$wmake_position_matrix(Main.hs:1025)
		at main.Main$compute_initial_state_x.thunkEnter(Main.hs:233)
		at eta.runtime.thunk.CAF.evaluate(CAF.java:35)
		at main.Main$ds1_s2BQ5.thunkEnter(Main.hs)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at main.Main$sat_s2BR8.thunkEnter(Main.hs)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at main.Main.$wsimple_loop(Main.hs:161)
		at main.Main$sat_s2CPO.thunkEnter(Main.hs)
		at eta.runtime.thunk.SingleEntryThunk.evaluate(SingleEntryThunk.java:22)
		at base.ghc.Base.zpzp(Base.hs:904)
		at base.ghc.Base$sat_sAHM.thunkEnter(Base.hs:798)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at base.ghc.Base.zpzp(Base.hs:904)
		at base.ghc.Base$sat_sAHM.thunkEnter(Base.hs:798)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at base.ghc.io.handle.Text.$wa7(Text.hs:586)
		at base.ghc.io.handle.Text.hPutStr2(Text.hs:553)
		at main.Main.main3(Main.hs)
		at main.Main.main2(Main.hs)
		at main.Main.main1(Main.hs)
		at main.Main$main1.applyV(Main.hs)
		at eta.runtime.exception.Exception.catch_(Exception.java:129)
		at main.Main.main10(Main.hs)
		at main.Main.DZCmain(Main.hs:53)
		at main.Main$DZCmain.applyV(Main.hs:53)
		at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
		at eta.runtime.stg.Capability.schedule(Capability.java:174)
		at eta.runtime.stg.Capability.scheduleClosure(Capability.java:119)
		at eta.runtime.Runtime.evalLazyIO(Runtime.java:170)
		at eta.runtime.Runtime.main(Runtime.java:163)
		at eta.main.main(Unknown Source)
```
