### ISSUE TITLE
how to access java public field

### ISSUE THREAD

**Issue by clojurians-org** [typelead/eta#685]
it read the java-interop doc:
  https://eta-lang.org/docs/eta-concepts/java-interop/java-ffi

it seems the public field access case is missing. 
it's a very common case, (System.out...)

**Comment by rahulmutt** [comment]
In fact the public case is the only case that works according to the " Importing Instance Fields " section. Honestly, it's a bit confusing so we'll use `System.out` as the example instead.

**Comment by clojurians-org** [comment]
i use the following code to run println method, it report those error, 
while i use IO type, it will success: [
Exception in thread "main" java.lang.NoClassDefFoundError: 
	at main.Main$$wa.applyV(Main.hs:15)
	at main.Main$main1.applyV(Main.hs)
	at main.Main$DZCmain.applyV(Main.hs)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
	at eta.runtime.stg.Capability.schedule(Capability.java:157)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: 
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)


```haskell
module Main where

import Java

data System = System @java.lang.System
  deriving Class

data PrintStream = PrintStream @java.io.PrintStream
  deriving Class

foreign import java unsafe "@static @field java.lang.System.out" getOut :: Java a PrintStream
foreign import java unsafe "println" println :: PrintStream -> String -> Java a ()
-- foreign import java unsafe "println" println :: PrintStream -> String -> IO ()

main :: IO ()
main = do
  out <- java $ getOut
  java $ println out "Hello World"

**Comment by rahulmutt** [comment]
@clojurians-org Can you report this as a separate issue since this looks like a bug? Thanks!
