### ISSUE TITLE
java FFI report ClassNotFoundException inside JavaMonad, but success inside IO monad

### ISSUE THREAD

**Issue by clojurians-org** [typelead/eta#686]
when i run the following code, i report the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: 
	at main.Main$$wa.applyV(Main.hs:15)
	at main.Main$main1.applyV(Main.hs)
	at main.Main$DZCmain.applyV(Main.hs)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
	at eta.runtime.stg.Capability.schedule(Capability.java:157)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: 
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

```haskell
module Main where

import Java

data System = System @java.lang.System
  deriving Class

data PrintStream = PrintStream @java.io.PrintStream
  deriving Class

foreign import java unsafe "@static @field java.lang.System.out" getOut :: Java a PrintStream
foreign import java unsafe "println" println :: PrintStream -> String -> Java a ()
-- foreign import java unsafe "println" println :: PrintStream -> String -> IO ()

main :: IO ()
main = do
  out <- java $ getOut
  java $ println out "Hello World"
```

when adjust to IO monad, it will success:

```haskell
foreign import java unsafe "println" println :: PrintStream -> String -> IO ()

main :: IO ()
main = do
  out <- java $ getOut
  println out "Hello World"
```

**Comment by rahulmutt** [comment]
If I recall correctly, we intentionally disallowed things like:
```
foreign import java unsafe "println" println :: PrintStream -> String -> Java a ()
```
and prefer:
```
foreign import java unsafe "println" println :: String -> Java PrintStream ()
```
so that you can write:
```
javaWith out $ println "Hello World"
```

But yes, there should've been a compile-time error telling you so, so this is a bug.
