### ISSUE TITLE
Missing line number information

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#693]
The following program (credits to @agocorona) has a space leak which produces a StackOverflowError:
```haskell
import Data.IORef

main :: IO ()
main = do
    r <- newIORef 0
    r <- sum r 1000000
    print r
  where
  sum r 0= do r <- readIORef r; print r
  sum r x= do
     modifyIORef r $ \v -> v + x
     sum r $ x - 1
```
The StackOverflowError here is not a problem - it's expected since there's a space leak.
```
Exception in thread "main" java.lang.StackOverflowError
	at integer.ghc.integer.Type.plusInteger(Type.hs:540)
	at main.Main$sat_s6AK.thunkEnter(Main.hs)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
	at integer.ghc.integer.Type.plusInteger(Type.hs:540)
	at main.Main$sat_s6AK.thunkEnter(Main.hs)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
	at integer.ghc.integer.Type.plusInteger(Type.hs:540)
	at main.Main$sat_s6AK.thunkEnter(Main.hs)
```
The problem here is that you'll notice that `main.Main$sat_s6AK` doesn't have a line number. In this case, the program is small and seeing the `plusInteger`, you can infer that `modifyIORef` is building up a large chain of chunks and you'd replace it with `modifyIORef'`. But this may be hard to read for large programs, so we should make sure line numbers are generated in cases like this.

@jneira There have been many layout changes in the codegen since you last worked on line numbers. I think the tweaks should be minor to be able to get back info for these cases.

**Comment by jneira** [comment]
Mmm, i think there were cases of programs without line numbers since the first implementation. Most times in the top level main module, but i think there were intermediate modules withouth them too.
I'll try to take a look.

**Comment by rahulmutt** [comment]
Hmm in that case I wonder if somewhere in the compilation pipeline, information is being discarded when it shouldn't be. I wonder if GHC 8 has resolved some of those issues since they've added DWARF support which means the info would have to be accurate.

**Comment by rahulmutt** [comment]
For reference this is Trac ticket on DWARF support: https://ghc.haskell.org/trac/ghc/ticket/10656
