### ISSUE TITLE
eta-benchmarks hangs when compiled with Eta

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta#709]
Reproduction Steps:
```
git clone https://github.com/typelead/eta-benchmarks
cd eta-benchmarks
etlas run
```

Output of `jstack -l [pid]`:
```
"Thread-2" #12 prio=5 os_prio=31 tid=0x00007faae67f7800 nid=0x5007 runnable [0x00007000010f1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:546)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:541)
	at eta.runtime.concurrent.Concurrent.takeMVar(Concurrent.java:67)
	at shake.general.Chunks$sat_s2MS1.applyV(Chunks.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at shake.general.Chunks$sat_s2MS2.applyV(Chunks.hs)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
	at eta.runtime.stg.Capability.schedule(Capability.java:175)
	at eta.runtime.concurrent.WorkerThread.run(WorkerThread.java:13)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=31 tid=0x00007faae480e800 nid=0x1703 runnable [0x0000700000216000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:546)
	at eta.runtime.stg.Capability.blockedLoop(Capability.java:541)
	at eta.runtime.concurrent.Concurrent.readMVar(Concurrent.java:87)
	at shake.development.shake.internal.core.Pool$sat_s4CE2.applyV(Pool.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at shake.development.shake.internal.core.Pool$sat_s4CFI.applyV(Pool.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at shake.development.shake.internal.core.Pool.runPool1(Pool.hs)
	at shake.development.shake.internal.core.Run$sat_s9QWQ.apply1V(Run.hs)
	at shake.development.shake.internal.core.Database$sat_s7UDU.apply2V(Database.hs)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:62)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:110)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:117)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at base.control.exception.Base$sat_sGIQ1.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at base.control.exception.Base$sat_sGIQE.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.control.exception.Base.finally1(Base.hs:277)
	at shake.general.Chunks$a6_s2MOV.apply1V(Chunks.hs)
	at shake.general.Chunks$sat_s2MSQ.applyV(Chunks.hs)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at shake.general.Chunks$sat_s2MSR.applyV(Chunks.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at shake.general.Chunks$sat_s2MT0.applyV(Chunks.hs)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at shake.general.Chunks.$wa5(Chunks.hs)
	at shake.development.shake.internal.core.Storage$sat_s6PBJ.apply1V(Storage.hs)
	at eta.runtime.apply.PAP1_1.applyV(PAP1_1.java:17)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:117)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at base.control.exception.Base$sat_sGIRM.applyV(Base.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at base.control.exception.Base$sat_sGIRZZ.applyV(Base.hs:262)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.control.exception.Base.bracket1(Base.hs:264)
	at shake.development.shake.internal.core.Storage.$wa1(Storage.hs)
	at shake.development.shake.internal.core.Database.$wa14(Database.hs)
	at shake.development.shake.internal.core.Run$sat_s9QXI.applyV(Run.hs)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:117)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at base.control.exception.Base$sat_sGIRM.applyV(Base.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at base.control.exception.Base$sat_sGIRZZ.applyV(Base.hs:262)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.control.exception.Base.bracket1(Base.hs:264)
	at extra.control.concurrent.Extra.withNumCapabilities1(Extra.hs)
	at shake.development.shake.internal.core.Run$sat_s9QXJ.applyV(Run.hs)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at base.control.exception.Base$sat_sGIQ1.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at base.control.exception.Base$sat_sGIQE.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.control.exception.Base.finally1(Base.hs:277)
	at shake.development.shake.internal.core.Run$a18_s9QIV.applyV(Run.hs)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:91)
	at base.control.exception.Base$sat_sGIQ1.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at base.control.exception.Base$sat_sGIQE.applyV(Base.hs:275)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42)
	at base.control.exception.Base.finally1(Base.hs:277)
	at shake.development.shake.internal.core.Run.$wa1(Run.hs)
	at shake.development.shake.internal.Shake.shake1(Shake.hs)
	at main.Main.$Lr1OWH$j(Build.hs)
	at main.Main.main3(Build.hs)
	at main.Main.main1(Build.hs)
	at main.Main$main1.applyV(Build.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:129)
	at main.Main.main94(Build.hs)
	at main.Main.DZCmain(Build.hs:161)
	at main.Main$DZCmain.applyV(Build.hs:161)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
	at eta.runtime.stg.Capability.schedule(Capability.java:175)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:120)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:222)
	at eta.runtime.Runtime.main(Runtime.java:215)
	at eta.main.main(Unknown Source)
```

It appears that the `main` Thread and `Thread-2` both are attempting to read from an MVar and waiting on it. Looks like some race condition and probably a bug in the concurrent runtime.

**Comment by rahulmutt** [comment]
I don't remember the fix, but `eta-benchmarks` no longer hangs on master.
