### ISSUE TITLE
etlas run cannot find class

### ISSUE THREAD

**Issue by dumptruckman** [typelead/eta#732]
I encoutered this error when trying to run my test project.
```etlas run eta-test
In order, the following will be built (use -v for more details):
 - eta-test-0.1.0.0 (exe:eta-test) (configuration changed)
Configuring executable 'eta-test' for eta-test-0.1.0.0..
Preprocessing executable 'eta-test' for eta-test-0.1.0.0..
Building executable 'eta-test' for eta-test-0.1.0.0..
? Successfully built 1 module. Way To Go!
Exception in thread "main" java.lang.NoClassDefFoundError: eta/runtime/stg/Closure
        at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.runtime.stg.Closure
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```

After some research, we've found that the classpath in the launcher jar's manifest does seem to point to the correct jars:
```Manifest-Version: 1.0
Class-Path: eta-test.jar \C:\Users\XX XXXXXXXXXXXX\AppData\Roaming\etl
 as\eta-0.7.2.1\base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF\base-4.8.2.0-IPFDt
 ZjmEfh5tPXF10v5hF.jar \C:\Users\XX XXXXXXXXXXXX\AppData\Roaming\etlas
 \eta-0.7.2.1\ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE\ghc-prim-0.4.0.0
 -Jhi6UgHuZdoBZWUpVo3WKE.jar \C:\Users\XX XXXXXXXXXXXX\AppData\Roaming
 \etlas\eta-0.7.2.1\integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm\integer-0.5
 .1.0-ACyqTmAMUMGGvisLFeQbAm.jar \C:\Users\XX XXXXXXXXXXXX\AppData\Roa
 ming\etlas\eta-0.7.2.1\rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w\rts-0.1.0.0
 -5Dj4qf1Wx9cCeYbpni5T1w.jar
Created-By: etlas-1.3.0.0
Main-Class: eta.main```

**Comment by jneira** [comment]
@dumptruckman one check more could be see if the .cmd is executing the exename.launcher.jar

**Comment by jneira** [comment]
I am afraid i cant reproduce the issue with last versions:
```
D:\ws\eta\eta-test>etlas --version && etlas exec eta -- --version
etlas version 1.3.0.0 compiled using version 2.1.0.0 of the etlas-cabal library
The Eta Programming Language Compiler, Version 0.7.2b1, Git Revision eba7e3347aa3392cd4bd21a80f735d661a024a05
D:\ws\eta\eta-test>etlas clean
cleaning...

D:\ws\eta\eta-test>etlas run
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - eta-test-0.1.0.0 (lib) (first run)
 - eta-test-0.1.0.0 (exe:eta-test-prog) (first run)
Configuring library for eta-test-0.1.0.0..
Preprocessing library for eta-test-0.1.0.0..
Building library for eta-test-0.1.0.0..
 [K [1m [32m✓ Successfully built 1 module. Way To Go! [0m

 [0mConfiguring executable 'eta-test-prog' for eta-test-0.1.0.0..
Preprocessing executable 'eta-test-prog' for eta-test-0.1.0.0..
Building executable 'eta-test-prog' for eta-test-0.1.0.0..
 [K [1m [32m✓ Successfully built 1 module. Mission Accomplished! [0m

 [0mdoes not exist (ioerr)
does not exist (ioerr)
JException java.io.FileNotFoundException: io ex
JException java.lang.Exception: ex
does not exist (java.io.FileNotFoundException: io ex)
does not exist (java.nio.file.NoSuchFileException: x)
```
My .cmd is:
```
@echo off
set DIR=%~dp0
if defined ETA_JAVA_CMD goto execute
if defined JAVA_HOME goto findJavaFromJavaHome
set ETA_JAVA_CMD=java.exe
goto execute
:findJavaFromJavaHome
set ETA_JAVA_HOME=%JAVA_HOME:"=%
set ETA_JAVA_CMD=%ETA_JAVA_HOME%\bin\java.exe
:execute
"%ETA_JAVA_CMD%" %JAVA_ARGS% %JAVA_OPTS% %ETA_JAVA_ARGS% -classpath "%DIR%\eta-test-prog.launcher.jar";%ETA_CLASSPATH% eta.main %*
```
@dumptruckman yours should be equal
btw, note i did an `etlas clean` before the `etlas run`
if all checks are ok:
* .cmd executes de exename.launcher.jar
* in exename.launcher.jar exists a ref to rts
* the jar referenced exists and it has inside the class not found
... we can try to execute the jar using `java` executable directly and try to set in the path the jar...

**Comment by jneira** [comment]
As commented by @dumptruckman in gitter the problem with the classpath is caused for paths with spaces: https://stackoverflow.com/questions/18659774/how-do-i-handle-files-with-spaces-in-the-classpath-in-manifest-mf
So we should replace spaces with `%20` in https://github.com/typelead/etlas/blob/master/etlas-cabal/Distribution/Simple/Eta.hs#L447-L466
Thanks for investigating this!

**Comment by dumptruckman** [comment]
After some research, the problem appears to be related to spaces in the paths of the library jars. They must be converted to %20 or we have this problem.

**Comment by dumptruckman** [comment]
The workaround for now is to use use uberjar mode.
