### ISSUE TITLE
ClassNotFoundException evaluating an IO function in a repl within wai-servlet-handler-jetty

### ISSUE THREAD

**Issue by jneira** [typelead/eta#756]
Trying to run a `wai-servlet` app:
```
C:\ws\eta\wai-servlet-handler-jetty>etlas repl
In order, the following will be built (use -v for more details):
 - wai-servlet-handler-jetty-0.1.2.0 (lib) (ephemeral targets)
Preprocessing library for wai-servlet-handler-jetty-0.1.2.0..
--- Welcome message ---
 Successful! One module loaded.
Prelude Network.Wai.Servlet.Handler.Jetty> :m +  Network.Wai.Servlet.Examples
Prelude Network.Wai.Servlet.Examples Network.Wai.Servlet.Handler.Jetty> run 3000 $ appAll "examples/index.html"
*** Exception: java.lang.RuntimeException: Failed during evalStmt of Eta REPL ex
pression
        at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:230)
        at eta.serv.Utils.evalStmt(Utils.java:31)
        at main.eta.repl.Run$sat_s1E2W.applyV(Run.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:129)
        at main.eta.repl.Run$sat_s1E30.applyV(Run.hs)
        at main.eta.repl.Run.$Lr1DTAa5(Run.hs)
        at main.eta.repl.Run$sat_s1E31.applyV(Run.hs)
        at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:
91)
        at main.eta.repl.Run$sat_s1E36.applyV(Run.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:129)
        at main.eta.repl.Run$sat_s1E37.applyV(Run.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:108)
        at eta.runtime.stg.Capability.schedule(Capability.java:183)
        at eta.runtime.concurrent.WorkerThread.run(WorkerThread.java:16)
Caused by: java.lang.RuntimeException: Failed during evalIOInternal of Eta REPL
expression
        at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:299)
        at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:223)
        ... 13 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:297)
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: wai_servlet_handler_jetty/network/wai
/servlet/handler/Jetty
        at interactive.EtaRepl1_3$sat_sPRZZ.thunkEnter(Interactive.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at eta.runtime.thunk.Thunk.apply1(Thunk.java:150)
        at base.ghc.Base.$(Base.hs)
        at base.ghc.Base$$.apply2(Base.hs)
        at interactive.EtaRepl1_3$sat_sPS2.thunkEnter(Interactive.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at base.ghc.Base.id(Base.hs:964)
        at base.ghc.Base$id.apply1(Base.hs:964)
        at interactive.EtaRepl1_3$sat_sPS3.thunkEnter(Interactive.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:120)
        at base.ghc.Base.bindIO1(Base.hs)
        at base.ghc.Base.bindIO(Base.hs:1067)
        at base.ghc.Base$bindIO.apply2V(Base.hs:1067)
        at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:64)
        at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:112)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:120)
        at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:
91)
        at base.control.exception.Base$sat_sGIRN.applyV(Base.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:129)
        at base.control.exception.Base$sat_sGIS0.applyV(Base.hs:262)
        at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:42
)
        at base.control.exception.Base.bracket1(Base.hs:264)
        at base.system.Environment.withArgs1(Environment.hs)
        at base.system.Environment.withArgs(Environment.hs:150)
        at base.system.Environment$withArgs.apply2V(Environment.hs:150)
        at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:64)
        at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:112)
        at eta.runtime.stg.Closures$EvalIO.enter(Closures.java:133)
        at eta.runtime.stg.Capability.schedule(Capability.java:183)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:123)
        at eta.runtime.Runtime.evalIO(Runtime.java:292)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: wai_servlet_handler_jetty.network.w
ai.servlet.handler.Jetty
        at java.net.URLClassLoader.findClass(Unknown Source)
        at eta.serv.REPLClassLoader$ChildREPLClassLoader.loadClass(REPLClassLoad
er.java:66)
        ... 52 more

Prelude Network.Wai.Servlet.Examples Network.Wai.Servlet.Handler.Jetty> [0m[0m
```

**Comment by NickSeagull** [comment]
Happened to me yesterday with a simple Hello World also

**Comment by rahulmutt** [comment]
With the recent master, I've tried both with OS X and the Windows node, and both gave the following output:

```
2018-06-08 20:36:52.322:INFO::Thread-2: Logging initialized @81773ms to org.eclipse.jetty.util.log.StdErrLog
2018-06-08 20:36:53.401:INFO:oejs.Server:Thread-2: jetty-9.4.5.v20170502
2018-06-08 20:36:53.476:INFO:oejs.AbstractConnector:Thread-2: Started ServerConnector@c44b495{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
2018-06-08 20:36:53.478:INFO:oejs.Server:Thread-2: Started @82935ms
it :: ()


```

**Comment by rahulmutt** [comment]
@NickSeagull Can you do a source installation and verify whether your bug still occurs? If so, it would be great if you can file a separate issue with the full details on how to reproduce it.

**Comment by jneira** [comment]
Works for me too in windows 10

**Comment by jneira** [comment]
I am afraid that after a first succesful execution, i am getting the same exception again. Dont know what can i did to trigger it (i've only reinstalled wai-servlet).

**Comment by rahulmutt** [comment]
@jneira Have you re-installed via `etlas install` or have you added it as a local dependency in your `cabal.project`?

**Comment by jneira** [comment]
@rahulmutt sorry for the false alarm, it was another exception caused by the fact that exiting the repl does not stop the jetty server (it should do it, right?): i have to manually kill the process

**Comment by jneira** [comment]
* Tested again in win 7 with java 1.8.0_101 and it throws the same `ClassNotFoundException` (i double checked it this time), i wonder if it is related with permissions

**Comment by jneira** [comment]
* After update my local eta-serv binary the `ClassNotFoundException` error is gone.. yay!
* @rahulmutt However the jetty serve continue running after exiting the repl

**Comment by rahulmutt** [comment]
I just realized why. We need to manually kill off all the active threads on RTS shutdown, which I think is not happening. Can you share the output of `jstack` after exiting a REPL that started a jetty server?
