### ISSUE TITLE
Eta on NixOS

### ISSUE THREAD

**Issue by NeQuissimus** [typelead/eta#827]
Pinging @puffnfresh :)

I am following this:
https://eta-lang.org/docs/user-guides/eta-user-guide/installation/nix

```bash
$ git clone --branch stable --recursive --depth 1 https://github.com/typelead/eta
$ cd eta
$ nix-shell -A eta-build-shell
```

The `nix-shell` command fails with the following:

```bash
Linking Setup ...
[ 1 of 84] Compiling Distribution.Simple.Program.Internal ( Distribution/Simple/Program/Internal.hs, /build/Distribution/Simple/Program/Internal.o )
[ 2 of 84] Compiling Distribution.Compat.MonadFail ( Distribution/Compat/MonadFail.hs, /build/Distribution/Compat/MonadFail.o )
[ 3 of 84] Compiling Distribution.Compat.GetShortPathName ( Distribution/Compat/GetShortPathName.hs, /build/Distribution/Compat/GetShortPathName.o )
[ 4 of 84] Compiling Distribution.GetOpt ( Distribution/GetOpt.hs, /build/Distribution/GetOpt.o )
[ 5 of 84] Compiling Distribution.Compat.Binary ( Distribution/Compat/Binary.hs, /build/Distribution/Compat/Binary.o )
[ 6 of 84] Compiling Distribution.Compat.Semigroup ( Distribution/Compat/Semigroup.hs, /build/Distribution/Compat/Semigroup.o )
[ 7 of 84] Compiling Distribution.Lex ( Distribution/Lex.hs, /build/Distribution/Lex.o )
[ 8 of 84] Compiling Distribution.TestSuite ( Distribution/TestSuite.hs, /build/Distribution/TestSuite.o )
[ 9 of 84] Compiling Distribution.Simple.PreProcess.Unlit ( Distribution/Simple/PreProcess/Unlit.hs, /build/Distribution/Simple/PreProcess/Unlit.o )
[10 of 84] Compiling Distribution.Simple.CCompiler ( Distribution/Simple/CCompiler.hs, /build/Distribution/Simple/CCompiler.o )
[11 of 84] Compiling Distribution.PackageDescription.Utils ( Distribution/PackageDescription/Utils.hs, /build/Distribution/PackageDescription/Utils.o )
[12 of 84] Compiling Distribution.Compat.ReadP ( Distribution/Compat/ReadP.hs, /build/Distribution/Compat/ReadP.o )
[13 of 84] Compiling Distribution.ReadE ( Distribution/ReadE.hs, /build/Distribution/ReadE.o )
[14 of 84] Compiling Distribution.Verbosity ( Distribution/Verbosity.hs, /build/Distribution/Verbosity.o )
[15 of 84] Compiling Distribution.Text ( Distribution/Text.hs, /build/Distribution/Text.o )
[16 of 84] Compiling Distribution.ModuleName ( Distribution/ModuleName.hs, /build/Distribution/ModuleName.o )
[17 of 84] Compiling Distribution.System ( Distribution/System.hs, /build/Distribution/System.o )
[18 of 84] Compiling Distribution.Version ( Distribution/Version.hs, /build/Distribution/Version.o )

Distribution/Version.hs:132:10:
    No instance for (Binary Version)
      arising from a use of ‘binary-0.7.5.0:Data.Binary.Class.$gdmput’
    In the expression: binary-0.7.5.0:Data.Binary.Class.$gdmput
    In an equation for ‘put’:
        put = binary-0.7.5.0:Data.Binary.Class.$gdmput
    In the instance declaration for ‘Binary VersionRange’
[22 of 84] Compiling Language.Haskell.Extension ( Language/Haskell/Extension.hs, /build/Language/Haskell/Extension.o )
[26 of 84] Compiling Distribution.Compat.Exception ( Distribution/Compat/Exception.hs, /build/Distribution/Compat/Exception.o )
[27 of 84] Compiling Distribution.Compat.Internal.TempFile ( Distribution/Compat/Internal/TempFile.hs, /build/Distribution/Compat/Internal/TempFile.o )
[28 of 84] Compiling Distribution.Compat.CopyFile ( Distribution/Compat/CopyFile.hs, /build/Distribution/Compat/CopyFile.o )
[41 of 84] Compiling Distribution.Compat.Environment ( Distribution/Compat/Environment.hs, /build/Distribution/Compat/Environment.o )
[72 of 84] Compiling Distribution.Compat.CreatePipe ( Distribution/Compat/CreatePipe.hs, /build/Distribution/Compat/CreatePipe.o )
builder for '/nix/store/al803zvbmbxshc61mg608v5yg80fwgyr-Cabal-1.24.2.0.drv' failed with exit code 1
cannot build derivation '/nix/store/gvldir7pcfs473578q34xllsfyh38y56-etlas-1.3.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/5479hwfpa9y53643vx7b12i4i604lpvz-eta-0.7.2.1.drv', '/nix/store/g5xyb6y6116fsw5wmspjd66lsxg68nr4-eta-build-0.0.0.drv', '/nix/store/gvldir7pcfs473578q34xllsfyh38y56-etlas-1.3.0.0.drv', '/nix/store/pxvhqxjg2p490c4ynnslpq2x62p9dxd6-eta-pkg-0.7.2.1.drv' failed
```

Note that I am using NixOS unstable, not quite sure that would really make a difference:

```bash
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`                               
 - host os: `Linux 4.17.10, NixOS, 18.09.git.443cbd7 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre145679.dae9cf6106d"`
 - channels(nequi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

So I figured I'd try a Gradle build:

https://eta-lang.org/docs/user-guides/eta-user-guide/installation/gradle

I checked out `eta-init` and ran the following:

```bash
λ nix-shell -p openjdk8

[nix-shell:~/dev/eta/eta-init]$ ./gradlew run
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :setupEnvironmentEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupEnvironmentEta'.
> IOException occurred when executing command [/home/nequi/.gradle/caches/etlas/1.4.0.0/etlas, init] with workingDir null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed
```

Here is the stack trace:

<details>
<summary>Expand stacktrace</summary>

<pre>
[nix-shell:~/dev/eta/eta-init]$ ./gradlew run --stacktrace
> Task :setupEnvironmentEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupEnvironmentEta'.
> IOException occurred when executing command [/home/nequi/.gradle/caches/etlas/1.4.0.0/etlas, init] with workingDir null

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':setupEnvironmentEta'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: IOException occurred when executing command [/home/nequi/.gradle/caches/etlas/1.4.0.0/etlas, init] with workingDir null
	at com.typelead.gradle.utils.CommandLine.start(CommandLine.java:207)
	at com.typelead.gradle.utils.CommandLine.executeAndConsumeOutputWithProcess(CommandLine.java:143)
	at com.typelead.gradle.utils.EtlasCommand.getWelcomeMessage(EtlasCommand.java:92)
	at com.typelead.gradle.eta.tasks.EtaSetupEnvironment.ensureTelemetryPreferencesAndUpdate(EtaSetupEnvironment.java:259)
	at com.typelead.gradle.eta.tasks.EtaSetupEnvironment.setupEnvironment(EtaSetupEnvironment.java:125)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 29 more
Caused by: java.io.IOException: Cannot run program "/home/nequi/.gradle/caches/etlas/1.4.0.0/etlas": error=2, No such file or directory
	at com.typelead.gradle.utils.CommandLine.start(CommandLine.java:205)
	... 47 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 48 more

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
</pre>
</details>

The `etlas` binary does exist but not all libraries can be linked:

```bash
[nix-shell:~/dev/eta/eta-init]$ ls -la /home/nequi/.gradle/caches/etlas/1.4.0.0/etlas
-rwxr--r-- 1 nequi users 26834736 Jul 26 16:39 /home/nequi/.gradle/caches/etlas/1.4.0.0/etlas

[nix-shell:~/dev/eta/eta-init]$ ldd !$
ldd /home/nequi/.gradle/caches/etlas/1.4.0.0/etlas
	linux-vdso.so.1 (0x00007ffe231dc000)
	libz.so.1 => not found
	librt.so.1 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/librt.so.1 (0x00007d6578256000)
	libutil.so.1 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libutil.so.1 (0x00007d6578053000)
	libdl.so.2 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libdl.so.2 (0x00007d6577e4f000)
	libgmp.so.10 => not found
	libm.so.6 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libm.so.6 (0x00007d6577aba000)
	libpthread.so.0 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libpthread.so.0 (0x00007d657789b000)
	libgcc_s.so.1 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libgcc_s.so.1 (0x00007d6577685000)
	libc.so.6 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/libc.so.6 (0x00007d65772d1000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007d657845e000)
```

**Comment by rahulmutt** [comment]
@NeQuissimus I think it's better to try building `master` since there have been lots of updates recently:

```
$ git clone --recursive --depth 1 https://github.com/typelead/eta
$ cd eta
$ nix-shell -A eta-build-shell
```

We aim to keep master as stable as possible and fix breakages pretty quickly.

We will update the instructions on the website.

**Comment by rahulmutt** [comment]
Instructions on the website are now updated (do a hard reload).

**Comment by NeQuissimus** [comment]
:) I was actually in the process of doing that already.
After what felt like building half the Haskell eco-system (I guess there were recent changes to the Haskell infrastructure in `nixpkgs` :D), I arrived at this:

```bash
[42 of 42] Compiling Hackage.Security.Client ( src/Hackage/Security/Client.hs, dist/build/Hackage/Security/Client.p_o )
ignoring (possibly broken) abi-depends field for packages
haddockPhase
installing
Installing library in /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2/lib/ghc-8.2.2/hackage-security-0.5.2.2
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2
shrinking /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2/lib/ghc-8.2.2/x86_64-linux-ghc-8.2.2/libHShackage-security-0.5.2.2-HvTGTxIgToKHrXmP96gDKy-ghc8.2.2.so
shrinking /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2/lib/ghc-8.2.2/hackage-security-0.5.2.2/HShackage-security-0.5.2.2-HvTGTxIgToKHrXmP96gDKy.o
wrong ELF type
strip is /nix/store/4qvrxzxa535y8304mk195x50b6p9607d-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2/lib
patching script interpreter paths in /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2
[4 of 4] Compiling Codec.Archive.Zip ( Codec/Archive/Zip.hs, dist/build/Codec/Archive/Zip.o )
checking for references to /build in /nix/store/rsga5kc7xyjg5kc9c92y04p6qs76h653-hackage-security-0.5.2.2...
wrong ELF type
building '/nix/store/nj22lm98idf7pi1k82h5wadk11k7a905-etlas-1.4.0.2.drv'...
[1 of 4] Compiling Codec.Archive.Zip.CP437 ( Codec/Archive/Zip/CP437.hs, dist/build/Codec/Archive/Zip/CP437.p_o )
setupCompilerEnvironmentPhase
Build with /nix/store/p372bagly14f82850qkzpjyimvw8ipqy-ghc-8.2.2.
ignoring (possibly broken) abi-depends field for packages
ignoring (possibly broken) abi-depends field for packages
unpacking sources
unpacking source archive /nix/store/h3qk9wp16ck6mkr24f68ff02499bdmmr-etlas
source root is etlas
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j4 -threaded -hide-package=etlas-cabal
<command line>: cannot satisfy -hide-package etlas-cabal
    (use -v for more information)
builder for '/nix/store/nj22lm98idf7pi1k82h5wadk11k7a905-etlas-1.4.0.2.drv' failed with exit code 1
error: build of '/nix/store/0m3v4jcyp7rcrv4n6pid7vcrw00216jb-eta-0.8.0.3.drv', '/nix/store/nj22lm98idf7pi1k82h5wadk11k7a905-etlas-1.4.0.2.drv' failed
```

**Comment by rahulmutt** [comment]
Try `git submodule update --init --recursive` and see if that helps. If that doesn't work, @puffnfresh will have to take a look.

**Comment by NeQuissimus** [comment]
@rahulmutt I did that right before `nix-shell -A eta-build-shell` since I switched from `stable` to `master` rather than checking out a new copy of the repo

**Comment by NeQuissimus** [comment]
Update: I tried whether an update to eta-lang/eta-nix would help but ran into NixOS/nixpkgs#44156 :disappointed:

**Comment by puffnfresh** [comment]
I don't get that error, but I do get an error about turtle:

```
Setup: Encountered missing dependencies:
turtle <1.4.5
```

Because stack2nix chooses turtle 1.5.8

**Comment by NeQuissimus** [comment]
Oh, I see @hvr recently introduced that boundary in 9b200f069584f06002d21a1c04fbd532dfa2584c.

**Comment by rahulmutt** [comment]
@NeQuissimus If you remove the boundary, does it still compile?

**Comment by hvr** [comment]
@rahulmutt I introduced that bound specifically because otherwise it failed to compile due to a nameclash that was introduced with that very version from the upper bound (I was too lazy to fix the nameclash...  :-) )

**Comment by NeQuissimus** [comment]
I don't even hit the boundary on my machine anyways. My build fails out earlier.

**Comment by hvr** [comment]
@NeQuissimus well, it seems you're trying to build Eta w/ GHC 8.2.2 ? If so, that's probably not going to work out of the box (I remember seeing some compile error); I know however that building Eta w/ GHC 7.10.3 works (I did so via `cabal --project=cabal.ghc.project new-build all` successfully...)

**Comment by NeQuissimus** [comment]
really? I am doing whatever the docs say, the nix derivation pulls in https://github.com/eta-lang/eta-nix, which specifically uses the stack file for 8.2.2. Why would that not work?!

**Comment by hvr** [comment]
@NeQuissimus oh, I didn't realise there was a stack file for GHC 8.2.2 ... (I'm trying to reproduce your problem with cabal as I can't use Stack)

**Comment by NeQuissimus** [comment]
@puffnfresh Using this diff, I now also hit the turtle dependency error:

```diff
diff --git a/default.nix b/default.nix
index 69d3cdc..168c15a 100644
--- a/default.nix
+++ b/default.nix
@@ -22,7 +22,6 @@ let
       # https://github.com/NixOS/nixpkgs/issues/24809
       preCompileBuildDriver = ''
         ${drv.preCompileBuildDriver or ""}
-        setupCompileFlags+=" -hide-package=etlas-cabal"
       '';
     });
     eta = haskell.lib.overrideCabal super.eta (drv: {
```

Also, what version of stack2nix are you using?
If I pull it from 18.03, I get this:

```bash
λ nix-shell -p stack2nix -I nixpkgs=/home/nequi/dev/nixpkgs --command "stack2nix --stack-yaml stack-8.2.2.yaml . > ../eta-nix/default.nix"
Invalid option `--stack-yaml'

Usage: stack2nix [--version] [--revision ARG] [-o ARG] URI
  Generate a nix expression for a Haskell package using stack
```

**Comment by rahulmutt** [comment]
@hvr @NeQuissimus To save the trouble for 7.10 and 8.2.2, I added a lower bound on `turtle` to 1.5.8 and updated the build script in 685ae9a0aacd5583e8e60bed1c6d73ea110246ed.

Does that help?

**Comment by NeQuissimus** [comment]
I sent a PR for the diff I posted above. Once that patch is applied, I can successfully run the steps from the docs.
