### ISSUE TITLE
ClassNotFoundException: eta.network.Utils using Scotty

### ISSUE THREAD

**Issue by politrons** [typelead/eta#904]
Hi,

Having this Gradle build

```
plugins {
    id 'com.typelead.eta' version '0.7.8'
    id 'application'
}

eta {
    version = '0.8.6b2'
    etlasVersion = '1.5.0.0'
}

repositories {
    mavenCentral()
    maven {
        url "http://repo.akka.io/snapshots/"
    }
}


dependencies {
    compile eta('base')
    compile eta('scotty')
    compile eta('warp:3.2.22')
    compile eta('http2:1.6.3')
    compile eta('file-embed')
    compile eta('bytestring')
    compile eta('aeson')
    compile eta('shakespeare')
    compile eta('blaze-html')
    compile eta('text')
    compile eta('template-haskell')
}
```
When I run the main file I have a problem with a` ClassNotFoundException: eta.network.Utils`

Here the complete Stack

> Task :run FAILED
"Starting Server at port 3000"
Setting phasers to stun... (port 3000) (ctrl-c to quit)
Exception in thread "main" java.lang.NoClassDefFoundError: eta/network/Utils
	at network.network.Socket$sat$234.thunkEnter(Socket.hs:1271)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at streaming_commons.data.streaming.Network.$Llvl6$1(Network.hs:174)
	at streaming_commons.data.streaming.Network$$Llvl6$1.apply1(Network.hs)
	at base.ghc.List.filter(List.hs:153)
	at streaming_commons.data.streaming.Network.bindPortGen7(Network.hs:175)
	at streaming_commons.data.streaming.Network.bindPortTCP1(Network.hs:453)
	at warp.network.wai.handler.warp.Run$sat$101.applyV(Run.hs:93)
	at base.control.exception.Base$sat$22.applyV(Base.hs:224)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:45)
	at base.control.exception.Base.bracket1(Base.hs:228)
	at warp.network.wai.handler.warp.Run.$wa1(Run.hs:94)
	at warp.network.wai.handler.warp.Run.run2(Run.hs)
	at scotty.web.scotty.Trans$sat$21.applyV(Trans.hs)
	at eta.runtime.apply.Function1.apply1V(Function1.java:14)
	at base.ghc.Base.bindIO1(Base.hs:1332)
	at base.ghc.Base$bindIO1.apply2V(Base.hs)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base.thenIO1(Base.hs:1338)
	at base.ghc.Base$thenIO1.apply2V(Base.hs)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at main.ScottyHttpServer.scottyServer1(ScottyHttpServer.hs:23)
	at main.ScottyHttpServer$scottyServer1.applyV(ScottyHttpServer.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:132)
	at main.Main.main1(Main.hs:7)
	at main.Main.DZCmain(Main.hs:7)
	at main.Main$DZCmain.applyV(Main.hs:7)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:125)
	at eta.runtime.stg.Capability.schedule(Capability.java:254)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:210)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:372)
	at eta.runtime.Runtime.main(Runtime.java:365)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.network.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

FAILURE: Build failed with an exception.

I'm using `Gradle 4.10.2 ` And I tried with Java Versions:

```
jdk1.8.0_161.jdk
Java 9
Java 10
Java 11
```

Cleaning the ~/.gradle did not help.

Is failing when interact with Scotty class `ScottyHttpServer`

Checking the cabal file in build generated we're using the network version `network == 2.6.3.2` 
But in the Cabal haskell project where I have this code working I have `network == 2.6.3.6` I dont know if it could be related

I also try to clean my .eta .etlas .gradle but same result

**Comment by jneira** [comment]
Hi, i am using gradle 4.7 in my succesful tests:
```console
PS C:\Users\Javier\dev\lang\eta\Eta-Haskell-server> gradle -version

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Windows 8.1 6.3 amd64
```
In fact [eta gradle examples](https://github.com/typelead/gradle-eta/tree/master/examples/simple) are using a gradle wrapper with that version, so maybe if you use the same wrapper it will work. Copy [the wrapper folder](https://github.com/typelead/gradle-eta/tree/master/examples/simple/gradle/wrapper) to your project should be enough.

**Comment by politrons** [comment]
Yes, all this time was an issue of Gradle as expected. Using the wrapper works. So it seems EtaLang has some issues with Gradle > 4.8 at least in my case.

Thanks a lot for all the help
