### ISSUE TITLE
'java.lang.NoClassDefFoundError: eta/primitive/Utils' when using JuicyPixels

### ISSUE THREAD

**Issue by y-taka-23** [typelead/eta#905]
The following runtime error occurs when I read/save images by JuicyPixels 3.3, despite the fact that eta-hackage supports the version (https://github.com/typelead/eta-hackage#graphics.)

The trouble can be re-produced even after clearing eta/etlas/gradle caches.

`src/main/eta/Main.hs`:
```haskell
module Main where

import Codec.Picture

main :: IO ()
main = do
    eitherImage <- readImage "sample.jpg"
    case eitherImage of
        Left err -> putStrLn $ "Error: " ++ err
        Right img -> saveJpgImage 80 "sample_copy.jpg" img
```

`build.gradle`:
```groovy
plugins {
    id 'com.typelead.eta' version '0.8.0'
    id 'application'
}

eta {
    version = '0.8.6b2'
    etlasVersion = '1.5.0.0'
}

dependencies {
    compile eta('base:4.11.1.0')
    compile eta('JuicyPixels:3.3')
}
```

The full log of `gradle run`:
```console
$ sudo rm -r ~/.gradle/caches/etlas/
$ sudo rm -r ~/.eta/
$ sudo rm -r ~/.etlas/
$ gradle clean run -PetaSendMetrics=false
Downloading the latest package lists from:
- hackage.haskell.org
- git@github.com/typelead/etlas-index

> Task :setupEnvironmentEta
Installing Eta v0.8.6b2

Updating binary package index.
Updating the eta-hackage patch set.
Downloading executable 'eta'...
Downloading executable 'eta-pkg'...
Downloading executable 'eta-serv.jar'...
Selected eta-0.8.6b2.
Downloading [binary] rts-0.1.0.0...
Downloading [binary] ghc-prim-0.4.0.0...
Downloading [binary] integer-0.5.1.0...
Downloading [binary] base-4.11.1.0...
Downloading [binary] eta-boot-meta-0.8.6...
Downloading [binary] array-0.5.2.0...
Downloading [binary] deepseq-1.4.3.0...
Downloading [binary] bytestring-0.10.8.2...
Downloading [binary] containers-0.5.10.2...
Downloading [binary] binary-0.8.5.1...
Downloading [binary] eta-repl-0.8.6.2...
Downloading [binary] filepath-1.4.1.2...
Downloading [binary] time-1.8.0.3...
Downloading [binary] directory-1.3.1.0...
Downloading [binary] eta-boot-0.8.6...
Downloading [binary] pretty-1.1.3.6...
Downloading [binary] eta-meta-0.8.6.2...
Downloading [binary] template-haskell-2.11.1.0...
Installing boot libraries...
Resolving dependencies...
Configuring rts-0.1.0.0...
Installed rts-0.1.0.0
Resolving dependencies...
Configuring ghc-prim-0.4.0.0...
Installed ghc-prim-0.4.0.0
Resolving dependencies...
Configuring integer-0.5.1.0...
Installed integer-0.5.1.0
Resolving dependencies...
Configuring base-4.11.1.0...
Installed base-4.11.1.0
Resolving dependencies...
Configuring eta-boot-meta-0.8.6...
Installed eta-boot-meta-0.8.6
Resolving dependencies...
Configuring array-0.5.2.0...
Installed array-0.5.2.0
Resolving dependencies...
Configuring deepseq-1.4.3.0...
Installed deepseq-1.4.3.0
Resolving dependencies...
Configuring bytestring-0.10.8.2...
Installed bytestring-0.10.8.2
Resolving dependencies...
Configuring containers-0.5.10.2...
Installed containers-0.5.10.2
Resolving dependencies...
Configuring binary-0.8.5.1...
Installed binary-0.8.5.1
Resolving dependencies...
Configuring eta-repl-0.8.6.2...
Installed eta-repl-0.8.6.2
Resolving dependencies...
Configuring filepath-1.4.1.2...
Installed filepath-1.4.1.2
Resolving dependencies...
Configuring time-1.8.0.3...
Installed time-1.8.0.3
Resolving dependencies...
Configuring directory-1.3.1.0...
Installed directory-1.3.1.0
Resolving dependencies...
Configuring eta-boot-0.8.6...
Installed eta-boot-0.8.6
Resolving dependencies...
Configuring pretty-1.1.3.6...
Installed pretty-1.1.3.6
Resolving dependencies...
Configuring eta-meta-0.8.6.2...
Installed eta-meta-0.8.6.2
Resolving dependencies...
Configuring template-haskell-2.11.1.0...
Installed template-haskell-2.11.1.0
Finished installing boot libraries.
Downloading [source] semigroups-0.18.5...
Downloading [source] transformers-0.5.5.0...
Downloading [source] mtl-2.2.2...
Downloading [source] primitive-0.6.4.0...
Downloading [source] zlib-0.6.1.2...
Downloading [source] vector-0.12.0.1...
Downloading [source] JuicyPixels-3.3...
Building transformers-0.5.5.0 (all, legacy fallback)...
Building semigroups-0.18.5 (lib)...
Building zlib-0.6.1.2 (lib)...
Building mtl-2.2.2 (lib)...
Building primitive-0.6.4.0 (lib)...
Building vector-0.12.0.1 (lib)...
Building JuicyPixels-3.3 (lib)...

> Task :run
Exception in thread "main" java.lang.NoClassDefFoundError: eta/primitive/Utils
        at juicypixels.codec.picture.Jpg.decodeJpegWithMetadata(Jpg.hs:589)
        at juicypixels.codec.Picture.decodeImageWithPaletteAndMetadata(Picture.hs:379)
        at juicypixels.codec.Picture.decodeImage(Picture.hs:392)
        at juicypixels.codec.Picture$sat$100.thunkEnter(Picture.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at main.Main.main1(Main.hs:6)
        at main.Main$main1.applyV(Main.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:132)
        at main.Main.main5(Main.hs)
        at main.Main.DZCmain(Main.hs:6)
        at main.Main$DZCmain.applyV(Main.hs:6)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:125)
        at eta.runtime.stg.Capability.schedule(Capability.java:254)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:210)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:372)
        at eta.runtime.Runtime.main(Runtime.java:365)
        at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.primitive.Utils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14m 0s
6 actionable tasks: 6 executed
```

**Comment by jneira** [comment]
Hi, there is a [similar known issue using the eta plugin with gradle version > 4.8](https://github.com/typelead/gradle-eta/issues/36). The suggested workaruound is copy the gradle wrapper files of [gradle-eta examples](https://github.com/typelead/gradle-eta/issues/36):
- `gradlew`/`gradlew.bat` at top
- `gradle/wrapper` folder
and run it with the copied script
Or maybe you are already using `4.7`/`4.8` version?

**Comment by y-taka-23** [comment]
That's it! Actually I used a pretty older Gradle. After upgrading `gradlew` to v4.8 it works, Thx!
