### ISSUE TITLE
ClassFormatError: Illegal class name "" in class file etabukkitplugin/EtaPlugin when loading a fat jar using a SecureClassLoader

### ISSUE THREAD

**Issue by Jannyboy11** [typelead/eta#923]
There is a class in the compiled class files or in the eta runtime that apparently has an empty name.

## Description

Bukkit is a minecraft mod api that loads plugins (deployed as jar files) using a custom PluginClassLoader which extends URLClassLoader. I used the the fat-jar example from the gradle-eta repo to include the eta runtime. 

PluginLoading works in three phases:
1. Bukkit's JavaPluginLoader instantiates Plugin objects by reading a plugin.yml file inside the plugin's jar. From there it finds the 'main' property which is the class name it will try to instantiate using reflection using a public zero-argument constructor.
2. The pluginloader calls onLoad on every plugin
3. The pluginloader class onEnable on every plugin

I used the java interop examples to export an EtaPlugin which extends JavaPlugin and I overrode the onEnable method. When the onEnable method executed the error was thrown.

## Expected Behavior

Expected my plugin to log "Hello from Eta!"

## Actual Behavior

The onEnable method threw an Error:
```
java.lang.ClassFormatError: Illegal class name "" in class file etabukkitplugin/EtaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:130) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:194) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.janboerman.hukkit.EtaPlugin.onEnable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Possible Fix

Don't generate classes with empty names.

## Steps to Reproduce

1. [Download BuildTools and compile Spigot](https://www.spigotmc.org/wiki/buildtools/) (the minecraft server implementation)
2. Run it using `java -jar spigot-<version>.jar` to generate necessary files
3. Accept Mojang's EULA by editing the eula.txt file.
4. Compile my [EtaPlugin](https://github.com/Jannyboy11/EtaBukkitPlugin) using the gradle task `shadowJar`
5. Drop the EtaBukkitPlugin-all.jar in the `<server_root>/plugins` folder.
5. Start the server again.
6. Watch the error being thrown.

## Context

The error makes my plugin completely useless as eta-generated classes cannot be classloaded.

## Your Environment

* Did you install an older version of Eta/Etlas before?
Yes, but I updated using `etlas update` and `etlas select latest`
* Current Eta & Etlas version:
PS C:\Users\Test> etlas --version
etlas version 1.5.0.0
compiled using version 2.1.0.0 of the etlas-cabal library
PS C:\Users\Test> eta --version
The Eta Programming Language Compiler, Version 0.7.2b1, Git Revision eba7e3347aa3392cd4bd21a80f735d661a024a05
* Operating System and version:
Windows 10, Java 11
* Link to your project:
https://github.com/Jannyboy11/EtaBukkitPlugin

**Comment by rahulmutt** [comment]
Perhaps you mean to write:

```haskell
foreign import java unsafe "@static java.util.logging.Logger.info" info :: JString -> Java a ()
```
instead of 
https://github.com/Jannyboy11/EtaBukkitPlugin/blob/master/src/main/eta/EtaPlugin.hs#L22

Let me know if that fixes it. I apologize for the obscure error. Foreign imports are going to be a lot easier with #647 in the near future.
