### ISSUE TITLE
StackOverflowError via megaparsec

### ISSUE THREAD

**Issue by joshsh** [typelead/eta#924]
A program that runs to completion in GHC is failing as follows:

```
 Exception in thread "main" java.lang.StackOverflowError
        at eta.runtime.apply.Function3_4.<init>(Function3_4.java:11)
        at megaparsec.text.megaparsec.Prim$sat$330.<init>(Prim.hs)
        at megaparsec.text.megaparsec.Prim.$La6$1(Prim.hs:326)
        at megaparsec.text.megaparsec.Prim.$LpBind$1(Prim.hs:390)
        at megaparsec.text.megaparsec.Prim$sat$364.enter(Prim.hs:379)
        at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:113)
        at eta.runtime.apply.PAPSlow.apply5(PAPSlow.java:351)
        at eta.runtime.apply.Function1.apply6(Function1.java:70)
        [... and so on for 1024 lines]
```

While there is a lot of repetition in the stack trace, it appears to repeat exactly only once every few hundred lines.

I have reduced the failure case to a small, if not minimal, example including an operation that takes in a command line argument, reads a predetermined Thrift file, and parses it. The original CLI, reader, and input file are much more complex, but paring this example down any further seems to cause the issue to disappear.

[example.tar.gz](https://github.com/typelead/eta/files/2753956/example.tar.gz)

See the attached archive. Unpack it, then build with `./gradlew build` and execute it with `./gradlew run -PetaSendMetrics=false --args="anything"`

**Comment by rahulmutt** [comment]
Turns out that `megaparsec-5.3.1` was being picked up because `language-thrift` put an upper bound on the version of `megaparsec`. Adding a patch for `megaparsec-5.3.1` w/ the trampoline fixed it. 

A `./gradlew updateEtlas` should fix it.

**Comment by joshsh** [comment]
LGTM. Thanks!
